<?php
namespace Database\Seeders;
use App\Models\{Menu,Permission,Role,RoleMenuPermission,User};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
class SecuritySeeder extends Seeder {
 public function run(): void {
  $permissions=[]; foreach(['view','create','edit','delete','release','reopen','approve','post','undo','reverse','export','print'] as $code) $permissions[$code]=Permission::firstOrCreate(['code'=>$code],['name'=>ucfirst($code)]);
  $adminRole=Role::firstOrCreate(['code'=>'ADMINISTRATOR'],['name'=>'Administrator','description'=>'Full ERP access','is_active'=>true]);
  $user=User::firstOrCreate(['email'=>'admin@erp.local'],['name'=>'ERP Administrator','password'=>Hash::make('ChangeMe123!'),'is_active'=>true]); $user->roles()->syncWithoutDetaching([$adminRole->id]);
  $parents=[];$sort=0; foreach([['SALES','Sales / AR'],['PURCHASE','Purchase / AP'],['INVENTORY','Inventory'],['FINANCE','Finance'],['MASTER','Master Data'],['CONFIG','Configuration'],['AUDIT','Audit']] as [$code,$label]) $parents[$code]=Menu::updateOrCreate(['code'=>'section.'.strtolower($code)],['label'=>$label,'sort_order'=>++$sort*100,'is_active'=>true]);
  $definitions=[
   [null,'dashboard','Dashboard','dashboard'],
   ['SALES','sales.request','Sales Requests','sales.documents.index'],['SALES','sales.order','Sales Orders','sales.documents.index'],['SALES','sales.shipment','Shipments','sales.documents.index'],['SALES','sales.invoice','Sales Invoices','sales.documents.index'],['SALES','sales.posted-shipment','Posted Shipments','posted.index'],['SALES','sales.posted-invoice','Posted Sales Invoices','posted.index'],['SALES','ledger.customers','Customer Ledger Entries','ledger.customers.index'],['SALES','sales.history','Sales History','reports.sales.history'],['SALES','sales.outstanding-orders','Outstanding Orders','reports.sales.outstanding-orders'],['SALES','sales.outstanding-shipments','Outstanding Shipments','reports.sales.outstanding-shipments'],['SALES','sales.customer-aging','Customer Aging','reports.sales.customer-aging'],
   ['PURCHASE','purchase.request','Purchase Requests','purchase.documents.index'],['PURCHASE','purchase.order','Purchase Orders','purchase.documents.index'],['PURCHASE','purchase.receipt','Receipts','purchase.documents.index'],['PURCHASE','purchase.invoice','Purchase Invoices','purchase.documents.index'],['PURCHASE','purchase.posted-receipt','Posted Receipts','posted.index'],['PURCHASE','purchase.posted-invoice','Posted Purchase Invoices','posted.index'],['PURCHASE','ledger.vendors','Vendor Ledger Entries','ledger.vendors.index'],['PURCHASE','purchase.history','Purchase History','reports.purchase.history'],['PURCHASE','purchase.outstanding-orders','Outstanding Orders','reports.purchase.outstanding-orders'],['PURCHASE','purchase.outstanding-receipts','Outstanding Receipts','reports.purchase.outstanding-receipts'],['PURCHASE','purchase.vendor-aging','Vendor Aging','reports.purchase.vendor-aging'],
   ['INVENTORY','master.items','Items','master.items.index'],['INVENTORY','inventory.locations','Locations / Bins','inventory.locations.index'],['INVENTORY','inventory.transfer-requests','Goods Transfer Requests','goods-transfer-requests.index'],['INVENTORY','inventory.transfers','Goods Transfers','goods-transfers.index'],['INVENTORY','ledger.items','Item Ledger Entries','ledger.items.index'],['INVENTORY','transactions.adjustment','Inventory Adjustment','adjustments.index'],['INVENTORY','inventory.stock-availability','Stock Availability','reports.inventory.stock-availability'],['INVENTORY','inventory.stock-movement','Stock Movement','reports.inventory.stock-movement'],['INVENTORY','inventory.stock-valuation','Stock Valuation','reports.inventory.stock-valuation'],
   ['FINANCE','master.coa','Chart of Accounts','master.coa.index'],['FINANCE','ledger.gl','General Ledger Entries','ledger.gl.index'],['FINANCE','finance.journal','Journal','reports.finance.journal'],['FINANCE','finance.trial-balance','Trial Balance','reports.finance.trial-balance'],['FINANCE','finance.balance-sheet','Balance Sheet','reports.finance.balance-sheet'],['FINANCE','finance.profit-loss','Profit & Loss','reports.finance.profit-loss'],
   ['MASTER','master.customers','Customers','master.customers.index'],['MASTER','master.vendors','Vendors','master.vendors.index'],['MASTER','master.item-categories','Item Categories','master.item-categories.index'],['MASTER','master.brands','Brands','master.brands.index'],['MASTER','master.uoms','Units of Measure','master.uoms.index'],['MASTER','master.price-levels','Price Level Master','master.price-levels.index'],['MASTER','pricing.price-levels','Item Price Levels','item-prices.index'],['MASTER','pricing.price-approval','Price Approval','price-approval.index'],['MASTER','pricing.price-updates','Price Updates','price-updates.index'],
   ['CONFIG','config.data-views','Company Data Views','dashboard'],['CONFIG','config.users','Users','config.users.index'],['CONFIG','config.roles','Roles','config.roles.index'],['CONFIG','config.menu-security','Menu Security','config.menu-security.index'],['CONFIG','config.permissions','Permissions','config.permissions.index'],['CONFIG','config.numbering','Number Series','config.numbering.index'],['CONFIG','config.posting-setup','Posting Setup','config.posting-setup.index'],['CONFIG','config.settings','System Settings','config.settings.index'],
   ['AUDIT','audit.activity-log','User Activity Log','audit.activity-log.index'],
  ];
  foreach($definitions as $i=>$d){[$parent,$code,$label,$route]=$d;$menu=Menu::updateOrCreate(['code'=>$code],['parent_id'=>$parent?$parents[$parent]->id:null,'label'=>$label,'route_name'=>$route,'sort_order'=>$i+1,'is_active'=>true]);foreach($permissions as $permission)RoleMenuPermission::firstOrCreate(['role_id'=>$adminRole->id,'menu_id'=>$menu->id,'permission_id'=>$permission->id]);}
  Menu::whereIn('code',['section.transactions','section.ledgers','master.warehouses'])->update(['is_active'=>false]);
  foreach($parents as $menu)foreach($permissions as $permission)RoleMenuPermission::firstOrCreate(['role_id'=>$adminRole->id,'menu_id'=>$menu->id,'permission_id'=>$permission->id]);
 }
}
