@extends('layouts.app')
@section('title',$record->document_no)
@section('content')
@php $authz=app(\App\Services\Security\MenuAuthorizationService::class); @endphp
<div class="d-flex justify-content-between mb-3"><div><h4 class="mb-0">{{ $record->document_no }}</h4><span class="status-badge status-{{ $record->status }}">{{ $record->status }}</span></div><a class="btn btn-outline-secondary" href="{{ route('goods-transfers.index') }}">Back</a></div><div class="card mb-3"><div class="card-body"><strong>Request:</strong> {{ $record->request?->document_no }}<br><strong>Business Unit:</strong> {{ $record->businessUnit?->code ?? '-' }}@if($record->businessUnit) - {{ $record->businessUnit->name }}@endif<br><strong>Route:</strong> {{ $record->sourceLocation?->code }}{{ $record->sourceBin?' / '.$record->sourceBin->code:'' }} → {{ $record->destinationLocation?->code }}{{ $record->destinationBin?' / '.$record->destinationBin->code:'' }}</div></div>
<div class="card mb-3"><table class="table mb-0"><thead><tr><th>Item</th><th>Transfer</th><th>Shipped</th><th>Received</th><th>In Transit</th><th>Cost</th></tr></thead><tbody>@foreach($record->lines as $l)<tr><td>{{ $l->item?->code }}</td><td>{{ number_format((float)$l->quantity,4) }}</td><td>{{ number_format((float)$l->shipped_quantity,4) }}</td><td>{{ number_format((float)$l->received_quantity,4) }}</td><td>{{ number_format((float)$l->shipped_quantity-(float)$l->received_quantity,4) }}</td><td>{{ number_format((float)$l->unit_cost,4) }}</td></tr>@endforeach</tbody></table></div>
<div class="d-flex gap-2 mb-3">@if($record->status==='OPEN')<form method="post" action="{{ route('goods-transfers.release',$record) }}">@csrf<button class="btn btn-warning">Release</button></form>@endif @if($record->status==='RELEASED')<form method="post" action="{{ route('goods-transfers.ship',$record) }}">@csrf<button class="btn btn-primary">Ship</button></form>@endif</div>
@if($record->status==='SHIPPED')<div class="card mb-3"><div class="card-header bg-white"><strong>Receive at Destination</strong></div><div class="card-body"><form method="post" action="{{ route('goods-transfers.receive',$record) }}">@csrf<table class="table"><thead><tr><th>Item</th><th>In Transit</th><th>Receive Now</th></tr></thead><tbody>@foreach($record->lines as $l)@php $remain=(float)$l->shipped_quantity-(float)$l->received_quantity; @endphp<tr><td>{{ $l->item?->code }}</td><td>{{ number_format($remain,4) }}</td><td><input class="form-control" type="number" step="0.0001" min="0" max="{{ $remain }}" name="lines[{{ $l->id }}]" value="0"></td></tr>@endforeach</tbody></table><input class="form-control mb-2" name="notes" placeholder="Receipt notes"><button class="btn btn-success">Post Receipt</button></form></div></div>@endif
@if(in_array($record->status,['SHIPPED','RECEIVED'],true)&&$authz->allows(auth()->user(),'inventory.transfers','undo'))<form method="post" action="{{ route('goods-transfers.undo',$record) }}" class="card card-body border-danger">@csrf<label class="form-label">UNDO reason</label><div class="d-flex gap-2"><input class="form-control" name="reason" required><button class="btn btn-outline-danger">UNDO Transfer</button></div></form>@endif
@endsection
