@extends('layouts.app')
@section('title',$employee->exists?'Edit Employee':'New Employee')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">{{ $employee->exists?'Edit':'New' }} Employee</h4><a class="btn btn-outline-secondary" href="{{ $employee->exists?route('hr.employees.show',$employee):route('hr.employees.index') }}">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ $employee->exists?route('hr.employees.update',$employee):route('hr.employees.store') }}">@csrf @if($employee->exists)@method('PUT')@endif
<div class="card mb-3"><div class="card-header bg-white fw-semibold">Identity & Employment</div><div class="card-body row g-3">
<div class="col-md-3"><label class="form-label">Employee Code</label><input class="form-control" name="employee_code" value="{{ old('employee_code',$employee->employee_code) }}" required></div>
<div class="col-md-6"><label class="form-label">Full Name</label><input class="form-control" name="full_name" value="{{ old('full_name',$employee->full_name) }}" required></div><div class="col-md-3"><label class="form-label">Nick Name</label><input class="form-control" name="nick_name" value="{{ old('nick_name',$employee->nick_name) }}"></div>
<div class="col-md-3"><label class="form-label">Birth Place</label><input class="form-control" name="birth_place" value="{{ old('birth_place',$employee->birth_place) }}"></div><div class="col-md-3"><label class="form-label">Birth Date</label><input type="date" class="form-control" name="birth_date" value="{{ old('birth_date',optional($employee->birth_date)->format('Y-m-d')) }}"></div><div class="col-md-3"><label class="form-label">Gender</label><select class="form-select" name="gender"><option value="">-</option>@foreach(['MALE'=>'Male','FEMALE'=>'Female'] as $v=>$l)<option value="{{ $v }}" @selected(old('gender',$employee->gender)===$v)>{{ $l }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Join Date</label><input type="date" class="form-control" name="join_date" value="{{ old('join_date',optional($employee->join_date)->format('Y-m-d')) }}"></div><div class="col-md-3"><label class="form-label">Original Join Date</label><input type="date" class="form-control" name="original_join_date" value="{{ old('original_join_date',optional($employee->original_join_date)->format('Y-m-d')) }}"></div><div class="col-md-3"><label class="form-label">Rejoin Date</label><input type="date" class="form-control" name="rejoin_date" value="{{ old('rejoin_date',optional($employee->rejoin_date)->format('Y-m-d')) }}"></div><div class="col-md-3"><label class="form-label">Termination Date</label><input type="date" class="form-control" name="termination_date" value="{{ old('termination_date',optional($employee->termination_date)->format('Y-m-d')) }}"></div>
<div class="col-md-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$employee->exists?$employee->is_active:true))><label class="form-check-label">Active</label></div></div>
</div></div>
<div class="card mb-3"><div class="card-header bg-white fw-semibold">Contact & Government</div><div class="card-body row g-3">
<div class="col-md-4"><label class="form-label">Work Email</label><input type="email" class="form-control" name="work_email" value="{{ old('work_email',$employee->work_email) }}"></div><div class="col-md-4"><label class="form-label">Personal Email</label><input type="email" class="form-control" name="personal_email" value="{{ old('personal_email',$employee->personal_email) }}"></div><div class="col-md-4"><label class="form-label">Phone</label><input class="form-control" name="phone" value="{{ old('phone',$employee->phone) }}"></div>
<div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="2">{{ old('address',$employee->address) }}</textarea></div>
<div class="col-md-4"><label class="form-label">Emergency Contact</label><input class="form-control" name="emergency_contact_name" value="{{ old('emergency_contact_name',$employee->emergency_contact_name) }}"></div><div class="col-md-4"><label class="form-label">Emergency Phone</label><input class="form-control" name="emergency_contact_phone" value="{{ old('emergency_contact_phone',$employee->emergency_contact_phone) }}"></div>
<div class="col-md-3"><label class="form-label">KTP</label><input class="form-control" name="ktp_no" value="{{ old('ktp_no',$employee->ktp_no) }}"></div><div class="col-md-3"><label class="form-label">NPWP</label><input class="form-control" name="npwp_no" value="{{ old('npwp_no',$employee->npwp_no) }}"></div><div class="col-md-3"><label class="form-label">BPJS Kesehatan</label><input class="form-control" name="bpjs_kesehatan_no" value="{{ old('bpjs_kesehatan_no',$employee->bpjs_kesehatan_no) }}"></div><div class="col-md-3"><label class="form-label">BPJS TK</label><input class="form-control" name="bpjs_ketenagakerjaan_no" value="{{ old('bpjs_ketenagakerjaan_no',$employee->bpjs_ketenagakerjaan_no) }}"></div>
</div></div>
<div class="card"><div class="card-header bg-white fw-semibold">Bank & Other</div><div class="card-body row g-3">
<div class="col-md-3"><label class="form-label">Payment Method</label><input class="form-control" name="payment_method" value="{{ old('payment_method',$employee->payment_method) }}"></div><div class="col-md-3"><label class="form-label">Bank</label><input class="form-control" name="bank_name" value="{{ old('bank_name',$employee->bank_name) }}"></div><div class="col-md-3"><label class="form-label">Account No.</label><input class="form-control" name="bank_account_no" value="{{ old('bank_account_no',$employee->bank_account_no) }}"></div><div class="col-md-3"><label class="form-label">Account Owner</label><input class="form-control" name="bank_account_owner" value="{{ old('bank_account_owner',$employee->bank_account_owner) }}"></div><div class="col-12"><label class="form-label">Remarks</label><textarea class="form-control" name="remarks" rows="2">{{ old('remarks',$employee->remarks) }}</textarea></div>
</div><div class="card-footer bg-white"><button class="btn btn-primary">Save Employee</button></div></div>
</form>
@endsection
