@extends('layouts.app')
@section('title','Employees')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Employee Master</h4><div class="text-muted small">Employee identity/master data. Organization assignment is kept separately as effective-dated Allocation History.</div></div><a class="btn btn-primary" href="{{ route('hr.employees.create') }}">+ New Employee</a></div>
<form class="row g-2 mb-3"><div class="col-md-5"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Code or employee name"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All Status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="col-auto"><button class="btn btn-outline-secondary">Filter</button></div></form>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee Code</th><th>Name</th><th>Join Date</th><th>Work Email</th><th>Phone</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($rows as $employee)<tr><td class="fw-semibold"><a href="{{ route('hr.employees.show',$employee) }}">{{ $employee->employee_code }}</a></td><td>{{ $employee->full_name }}</td><td>{{ optional($employee->join_date)->format('d/m/Y') ?? '-' }}</td><td>{{ $employee->work_email ?? '-' }}</td><td>{{ $employee->phone ?? '-' }}</td><td><span class="badge {{ $employee->is_active?'text-bg-success':'text-bg-secondary' }}">{{ $employee->is_active?'ACTIVE':'INACTIVE' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('hr.employees.edit',$employee) }}">Edit</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No employee data.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $rows->links() }}</div>
@endsection
