@extends('layouts.app')
@section('title',$employee->employee_code.' - '.$employee->full_name)
@section('content')
<div class="d-flex justify-content-between align-items-start mb-3"><div><h4 class="mb-1">{{ $employee->employee_code }} - {{ $employee->full_name }}</h4><div class="text-muted">{{ $employee->work_email ?: $employee->phone }}</div></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('hr.employees.edit',$employee) }}">Edit Employee</a><a class="btn btn-primary" href="{{ route('hr.allocations.create',['employee_id'=>$employee->id]) }}">+ Allocation</a></div></div>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">Join Date</div><div class="fw-semibold">{{ optional($employee->join_date)->format('d/m/Y') ?? '-' }}</div><hr><div class="text-muted small">Status</div><div>{{ $employee->is_active?'Active':'Inactive' }}</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">KTP</div><div>{{ $employee->ktp_no ?: '-' }}</div><div class="text-muted small mt-2">NPWP</div><div>{{ $employee->npwp_no ?: '-' }}</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">Bank</div><div>{{ $employee->bank_name ?: '-' }}</div><div class="text-muted small mt-2">Account</div><div>{{ $employee->bank_account_no ?: '-' }}</div></div></div></div></div>
<div class="card"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Employee Allocation History</strong><span class="small text-muted">Payroll later resolves allocation by effective period, not today's latest row.</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Effective</th><th>Business Unit</th><th>Department</th><th>Position</th><th>Office</th><th>Payroll Group</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($employee->allocations as $a)<tr><td>{{ optional($a->effective_from)->format('d/m/Y') }} → {{ optional($a->effective_to)->format('d/m/Y') ?: 'Current' }}</td><td>{{ $a->businessUnit?->code ?? '-' }}</td><td>{{ $a->department?->name ?? '-' }}@if($a->subDepartment)<div class="small text-muted">{{ $a->subDepartment->name }}</div>@endif</td><td>{{ $a->position?->name ?? '-' }}</td><td>{{ $a->officeLocation?->name ?? '-' }}</td><td>{{ $a->payrollGroup?->name ?? '-' }}</td><td>{{ $a->employment_status ?: '-' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('hr.allocations.edit',$a) }}">Edit</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No allocation history yet.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
