<?php

namespace App\Services\Reports\Export;

use App\Models\Reports\ReportDefinition;
use App\Models\User;
use App\Services\Reports\{ReportColumn, ReportResult};
use RuntimeException;
use ZipArchive;

final class ReportXlsxExporter
{
    public function build(
        ReportDefinition $definition,
        ReportResult $result,
        array $parameters,
        User $user,
        string $databaseName,
    ): string {
        if (! class_exists(ZipArchive::class)) {
            throw new RuntimeException('PHP ZIP extension is required for XLSX export.');
        }

        $dir = storage_path('app/report-exports');
        if (! is_dir($dir) && ! mkdir($dir, 0775, true) && ! is_dir($dir)) {
            throw new RuntimeException('Unable to create report export directory.');
        }

        $path = $dir.'/'.uniqid('cgone-report_', true).'.xlsx';
        $zip = new ZipArchive();

        if ($zip->open($path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException('Unable to create XLSX file.');
        }

        $zip->addFromString('[Content_Types].xml', $this->contentTypes());
        $zip->addFromString('_rels/.rels', $this->rootRels());
        $zip->addFromString('xl/workbook.xml', $this->workbook());
        $zip->addFromString('xl/_rels/workbook.xml.rels', $this->workbookRels());
        $zip->addFromString('xl/styles.xml', $this->styles());
        $zip->addFromString(
            'xl/worksheets/sheet1.xml',
            $this->sheetXml($definition, $result, $parameters, $user, $databaseName)
        );
        $zip->close();

        return $path;
    }

    private function sheetXml(
        ReportDefinition $definition,
        ReportResult $result,
        array $parameters,
        User $user,
        string $databaseName,
    ): string {
        $rows = [];
        $rows[] = [['CGOne ERP', 'text', 1]];
        $rows[] = [[$definition->name, 'text', 1]];
        $rows[] = [['Database', 'text', 1], [$databaseName, 'text', 0]];
        $rows[] = [['Generated By', 'text', 1], [$user->name, 'text', 0]];
        $rows[] = [['Generated At', 'text', 1], [now()->format('d/m/Y H:i:s'), 'text', 0]];

        foreach ($parameters as $key => $value) {
            $rows[] = [[ucwords(str_replace('_', ' ', $key)), 'text', 1], [$value === null || $value === '' ? 'ALL' : (string) $value, 'text', 0]];
        }

        $rows[] = [];

        $header = [];
        foreach ($result->columns as $column) {
            $header[] = [$column->label, 'text', 1];
        }
        $rows[] = $header;

        foreach ($result->rows as $row) {
            $line = [];
            foreach ($result->columns as $column) {
                $line[] = [
                    $result->value($row, $column->key),
                    $column->type,
                    $this->styleFor($column),
                ];
            }
            $rows[] = $line;
        }

        if ($result->totals !== []) {
            $totalLine = [];
            foreach ($result->columns as $i => $column) {
                if ($i === 0) {
                    $totalLine[] = ['GRAND TOTAL', 'text', 1];
                    continue;
                }
                $totalLine[] = [
                    array_key_exists($column->key, $result->totals) ? $result->totals[$column->key] : '',
                    $column->type,
                    $this->styleFor($column, true),
                ];
            }
            $rows[] = $totalLine;
        }

        $sheetData = '';
        foreach ($rows as $rowIndex => $cells) {
            $excelRow = $rowIndex + 1;
            $cellXml = '';
            foreach ($cells as $columnIndex => $cell) {
                [$value, $type, $style] = $cell;
                $ref = $this->columnLetter($columnIndex + 1).$excelRow;
                $cellXml .= $this->cellXml($ref, $value, $type, $style);
            }
            $sheetData .= '<row r="'.$excelRow.'">'.$cellXml.'</row>';
        }

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            .'<sheetViews><sheetView workbookViewId="0"/></sheetViews>'
            .'<sheetFormatPr defaultRowHeight="15"/>'
            .'<sheetData>'.$sheetData.'</sheetData>'
            .'</worksheet>';
    }

    private function cellXml(string $ref, mixed $value, string $type, int $style): string
    {
        if (is_numeric($value) && in_array($type, ['money','number','quantity','percent'], true)) {
            return '<c r="'.$ref.'" s="'.$style.'" t="n"><v>'.(float) $value.'</v></c>';
        }

        $text = $value === null ? '' : (string) $value;

        return '<c r="'.$ref.'" s="'.$style.'" t="inlineStr"><is><t xml:space="preserve">'
            .$this->xml($text)
            .'</t></is></c>';
    }

    private function styleFor(ReportColumn $column, bool $bold = false): int
    {
        if ($bold) {
            return 1;
        }

        if ($column->type === 'quantity' || ($column->type === 'money' && $column->decimals >= 4)) {
            return 3;
        }

        if (in_array($column->type, ['money','number','percent'], true)) {
            return 2;
        }

        return 0;
    }

    private function columnLetter(int $number): string
    {
        $letters = '';
        while ($number > 0) {
            $number--;
            $letters = chr(65 + ($number % 26)).$letters;
            $number = intdiv($number, 26);
        }
        return $letters;
    }

    private function xml(string $value): string
    {
        return htmlspecialchars($value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
    }

    private function contentTypes(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            .'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            .'<Default Extension="xml" ContentType="application/xml"/>'
            .'<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
            .'<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
            .'<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
            .'</Types>';
    }

    private function rootRels(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            .'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
            .'</Relationships>';
    }

    private function workbook(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
            .'<sheets><sheet name="Report" sheetId="1" r:id="rId1"/></sheets></workbook>';
    }

    private function workbookRels(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            .'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
            .'<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
            .'</Relationships>';
    }

    private function styles(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            .'<numFmts count="2"><numFmt numFmtId="164" formatCode="#,##0.00"/><numFmt numFmtId="165" formatCode="#,##0.0000"/></numFmts>'
            .'<fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts>'
            .'<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>'
            .'<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>'
            .'<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
            .'<cellXfs count="4">'
            .'<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
            .'<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0"/>'
            .'<xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>'
            .'<xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>'
            .'</cellXfs>'
            .'</styleSheet>';
    }
}
