<?php
namespace App\Http\Controllers\MasterData;
use App\Models\Customer;
class CustomerController extends AbstractMasterController {
 protected string $modelClass=Customer::class; protected string $menuCode='master.customers'; protected string $title='Customers'; protected array $columns=['code'=>'Code','name'=>'Name','email'=>'Email','credit_limit'=>'Credit Limit','multi_price_level'=>'Multi Price'];
 protected array $fields=['code'=>['label'=>'Code','type'=>'text'],'name'=>['label'=>'Name','type'=>'text'],'address'=>['label'=>'Billing Address','type'=>'textarea'],'billing_city'=>['label'=>'Billing City','type'=>'text'],'billing_state'=>['label'=>'Billing State','type'=>'text'],'billing_country'=>['label'=>'Billing Country','type'=>'text'],'shipping_address'=>['label'=>'Shipping Address','type'=>'textarea'],'shipping_city'=>['label'=>'Shipping City','type'=>'text'],'shipping_state'=>['label'=>'Shipping State','type'=>'text'],'shipping_country'=>['label'=>'Shipping Country','type'=>'text'],'phone'=>['label'=>'Phone','type'=>'text'],'email'=>['label'=>'Email','type'=>'email'],'npwp'=>['label'=>'NPWP','type'=>'text'],'payment_term_days'=>['label'=>'Payment Term (Days)','type'=>'number'],'customer_posting_group_id'=>['label'=>'Customer Posting Group','type'=>'select','options'=>'customer_groups','nullable'=>true],'tax_posting_group_id'=>['label'=>'Tax Posting Group','type'=>'select','options'=>'tax_groups','nullable'=>true],'default_price_level_id'=>['label'=>'Default Price Level','type'=>'select','options'=>'price_levels','nullable'=>true],'multi_price_level'=>['label'=>'Allow Multi Price Level','type'=>'checkbox'],'receivable_account_id'=>['label'=>'Receivable Account (fallback)','type'=>'select','options'=>'accounts','nullable'=>true],'credit_limit'=>['label'=>'Credit Limit','type'=>'number','step'=>'0.0001'],'is_active'=>['label'=>'Active','type'=>'checkbox']];
 protected function rules(?int $id=null): array{return ['code'=>$this->uniqueCode($id),'name'=>['required','string','max:255'],'address'=>['nullable','string'],'billing_city'=>['nullable','string','max:255'],'billing_state'=>['nullable','string','max:255'],'billing_country'=>['nullable','string','max:255'],'shipping_address'=>['nullable','string'],'shipping_city'=>['nullable','string','max:255'],'shipping_state'=>['nullable','string','max:255'],'shipping_country'=>['nullable','string','max:255'],'phone'=>['nullable','string','max:50'],'email'=>['nullable','email','max:255'],'npwp'=>['nullable','string','max:80'],'payment_term_days'=>['required','integer','min:0'],'customer_posting_group_id'=>['nullable','exists:customer_posting_groups,id'],'tax_posting_group_id'=>['nullable','exists:tax_posting_groups,id'],'default_price_level_id'=>['nullable','exists:price_levels,id'],'multi_price_level'=>['required','boolean'],'receivable_account_id'=>['nullable','exists:chart_of_accounts,id'],'credit_limit'=>['required','numeric','min:0'],'is_active'=>['required','boolean']];}
 protected function options(): array{return ['accounts'=>\App\Models\ChartOfAccount::where('is_active',true)->where('allow_posting',true)->orderBy('code')->get()->mapWithKeys(fn($a)=>[$a->id=>$a->code.' - '.$a->name]),'customer_groups'=>\App\Models\CustomerPostingGroup::where('is_active',true)->orderBy('code')->get()->mapWithKeys(fn($g)=>[$g->id=>$g->code.' - '.$g->name]),'tax_groups'=>\App\Models\TaxPostingGroup::where('is_active',true)->orderBy('code')->get()->mapWithKeys(fn($g)=>[$g->id=>$g->code.' - '.$g->name]),'price_levels'=>\App\Models\PriceLevel::where('is_active',true)->orderBy('sort_order')->pluck('name','id')];}
 protected function dataViewFields(): array {return ['code'=>['label'=>'Customer Code','type'=>'text','column'=>'code'],'name'=>['label'=>'Customer Name','type'=>'text','column'=>'name'],'email'=>['label'=>'Email','type'=>'text','column'=>'email'],'phone'=>['label'=>'Phone','type'=>'text','column'=>'phone'],'billing_city'=>['label'=>'City','type'=>'text','column'=>'billing_city'],'credit_limit'=>['label'=>'Credit Limit','type'=>'number','column'=>'credit_limit'],'default_price_level'=>['label'=>'Default Price Level','type'=>'lookup','relation'=>'defaultPriceLevel','column'=>'code'],'multi_price_level'=>['label'=>'Multi Price','type'=>'boolean','column'=>'multi_price_level'],'is_active'=>['label'=>'Active','type'=>'boolean','column'=>'is_active']];}
}
