<?php
namespace App\Http\Controllers\MasterData;
use App\Models\Item;
class ItemController extends AbstractMasterController {
 protected string $modelClass=Item::class; protected string $menuCode='master.items'; protected string $title='Items';
 protected array $columns=['code'=>'Code','name'=>'Name','item_type'=>'Type','price_hold'=>'Price Hold','is_discontinued'=>'Discontinued'];
 protected array $fields=[
 'code'=>['label'=>'Code','type'=>'text'],'name'=>['label'=>'Name','type'=>'text'],'item_type'=>['label'=>'Item Type','type'=>'select','options'=>'item_types'],'base_uom_id'=>['label'=>'Base UOM','type'=>'select','options'=>'uoms'],
 'category_id'=>['label'=>'Category','type'=>'select','options'=>'categories','nullable'=>true],'brand_id'=>['label'=>'Brand','type'=>'select','options'=>'brands','nullable'=>true],'default_vendor_id'=>['label'=>'Default Vendor','type'=>'select','options'=>'vendors','nullable'=>true],'costing_method'=>['label'=>'Costing Method','type'=>'text','nullable'=>true],'procurement_method'=>['label'=>'Procurement Method','type'=>'text','nullable'=>true],
 'min_quantity'=>['label'=>'Min Quantity','type'=>'number','step'=>'0.0001'],'max_quantity'=>['label'=>'Max Quantity','type'=>'number','step'=>'0.0001'],'reorder_level'=>['label'=>'Reorder Level','type'=>'number','step'=>'0.0001'],'min_order'=>['label'=>'Min Order','type'=>'number','step'=>'0.0001'],'lead_time_days'=>['label'=>'Lead Time Days','type'=>'number'],
 'inventory_posting_group_id'=>['label'=>'Inventory Posting Group','type'=>'select','options'=>'inventory_groups','nullable'=>true],'general_product_posting_group_id'=>['label'=>'General Product Posting Group','type'=>'select','options'=>'product_groups','nullable'=>true],'tax_posting_group_id'=>['label'=>'Tax Posting Group','type'=>'select','options'=>'tax_groups','nullable'=>true],
 'inventory_account_id'=>['label'=>'Inventory Account (fallback)','type'=>'select','options'=>'accounts','nullable'=>true],'sales_account_id'=>['label'=>'Sales Account (fallback)','type'=>'select','options'=>'accounts','nullable'=>true],'cogs_account_id'=>['label'=>'COGS Account (fallback)','type'=>'select','options'=>'accounts','nullable'=>true],'purchase_account_id'=>['label'=>'Purchase Account (fallback)','type'=>'select','options'=>'accounts','nullable'=>true],'adjustment_account_id'=>['label'=>'Adjustment Account','type'=>'select','options'=>'accounts','nullable'=>true],
 'specification'=>['label'=>'Specification','type'=>'textarea','nullable'=>true],'remarks'=>['label'=>'Remarks','type'=>'textarea','nullable'=>true],'can_be_sold'=>['label'=>'Can Be Sold','type'=>'checkbox'],'can_be_purchased'=>['label'=>'Can Be Purchased','type'=>'checkbox'],'is_discontinued'=>['label'=>'Discontinued','type'=>'checkbox'],'is_active'=>['label'=>'Active','type'=>'checkbox'] ];
 protected function rules(?int $id=null): array {return ['code'=>$this->uniqueCode($id),'name'=>['required','string','max:255'],'item_type'=>['required','in:INVENTORY,SERVICE,NON_INVENTORY'],'base_uom_id'=>['required','exists:uoms,id'],'category_id'=>['nullable','exists:item_categories,id'],'brand_id'=>['nullable','exists:brands,id'],'default_vendor_id'=>['nullable','exists:vendors,id'],'costing_method'=>['nullable','string','max:40'],'procurement_method'=>['nullable','string','max:40'],'min_quantity'=>['required','numeric','min:0'],'max_quantity'=>['required','numeric','min:0'],'reorder_level'=>['required','numeric','min:0'],'min_order'=>['required','numeric','min:0'],'lead_time_days'=>['required','integer','min:0'],'inventory_posting_group_id'=>['nullable','exists:inventory_posting_groups,id'],'general_product_posting_group_id'=>['nullable','exists:general_product_posting_groups,id'],'tax_posting_group_id'=>['nullable','exists:tax_posting_groups,id'],'inventory_account_id'=>['nullable','exists:chart_of_accounts,id'],'sales_account_id'=>['nullable','exists:chart_of_accounts,id'],'cogs_account_id'=>['nullable','exists:chart_of_accounts,id'],'purchase_account_id'=>['nullable','exists:chart_of_accounts,id'],'adjustment_account_id'=>['nullable','exists:chart_of_accounts,id'],'specification'=>['nullable','string'],'remarks'=>['nullable','string'],'can_be_sold'=>['required','boolean'],'can_be_purchased'=>['required','boolean'],'is_discontinued'=>['required','boolean'],'is_active'=>['required','boolean']];}
 protected function options(): array {$accounts=\App\Models\ChartOfAccount::where('is_active',true)->where('allow_posting',true)->orderBy('code')->get()->mapWithKeys(fn($a)=>[$a->id=>$a->code.' - '.$a->name]);return ['item_types'=>['INVENTORY'=>'Inventory','SERVICE'=>'Service','NON_INVENTORY'=>'Non Inventory'],'uoms'=>\App\Models\Uom::where('is_active',true)->orderBy('code')->pluck('name','id'),'categories'=>\App\Models\ItemCategory::where('is_active',true)->orderBy('code')->pluck('name','id'),'brands'=>\App\Models\Brand::where('is_active',true)->orderBy('code')->pluck('name','id'),'vendors'=>\App\Models\Vendor::where('is_active',true)->orderBy('code')->get()->mapWithKeys(fn($v)=>[$v->id=>$v->code.' - '.$v->name]),'accounts'=>$accounts,'inventory_groups'=>\App\Models\InventoryPostingGroup::where('is_active',true)->orderBy('code')->get()->mapWithKeys(fn($g)=>[$g->id=>$g->code.' - '.$g->name]),'product_groups'=>\App\Models\GeneralProductPostingGroup::where('is_active',true)->orderBy('code')->get()->mapWithKeys(fn($g)=>[$g->id=>$g->code.' - '.$g->name]),'tax_groups'=>\App\Models\TaxPostingGroup::where('is_active',true)->orderBy('code')->get()->mapWithKeys(fn($g)=>[$g->id=>$g->code.' - '.$g->name])];}
 protected function dataViewFields(): array {return ['code'=>['label'=>'Item Code','type'=>'text','column'=>'code'],'name'=>['label'=>'Item Name','type'=>'text','column'=>'name'],'item_type'=>['label'=>'Item Type','type'=>'text','column'=>'item_type'],'category'=>['label'=>'Category','type'=>'lookup','relation'=>'category','column'=>'name'],'brand'=>['label'=>'Brand','type'=>'lookup','relation'=>'brand','column'=>'name'],'default_vendor'=>['label'=>'Default Vendor','type'=>'lookup','relation'=>'defaultVendor','column'=>'code'],'costing_method'=>['label'=>'Costing Method','type'=>'text','column'=>'costing_method'],'procurement_method'=>['label'=>'Procurement','type'=>'text','column'=>'procurement_method'],'min_quantity'=>['label'=>'Min Qty','type'=>'number','column'=>'min_quantity'],'max_quantity'=>['label'=>'Max Qty','type'=>'number','column'=>'max_quantity'],'reorder_level'=>['label'=>'Reorder Level','type'=>'number','column'=>'reorder_level'],'price_hold'=>['label'=>'Price Hold','type'=>'boolean','column'=>'price_hold'],'is_discontinued'=>['label'=>'Discontinued','type'=>'boolean','column'=>'is_discontinued'],'is_active'=>['label'=>'Active','type'=>'boolean','column'=>'is_active']];}
}
