<?php
namespace App\Http\Controllers\HumanCapital\Time;

use App\Http\Controllers\Controller;
use App\Http\Requests\HumanCapital\Time\{SaveScheduleOverrideRequest,SaveShiftAssignmentRequest,SaveShiftPatternRequest};
use App\Models\HumanCapital\Employee;
use App\Models\HumanCapital\Time\{EmployeeShiftAssignment,Shift,ShiftPattern,ShiftPatternDay,WorkScheduleOverride};
use App\Services\Audit\ActivityLogService;
use App\Services\Security\MenuAuthorizationService;
use DomainException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

final class ScheduleController extends Controller
{
    public function __construct(private readonly MenuAuthorizationService $authz,private readonly ActivityLogService $audit){}
    public function index():View{$this->gate('view');$patterns=ShiftPattern::with('days.shift')->orderByDesc('is_active')->orderBy('code')->get();$assignments=EmployeeShiftAssignment::with(['employee','pattern'])->orderByDesc('effective_from')->paginate(20,['*'],'assignment_page')->withQueryString();$overrides=WorkScheduleOverride::with(['employee','shift'])->orderByDesc('work_date')->limit(50)->get();$employees=Employee::where('is_active',true)->orderBy('employee_code')->get();$shifts=Shift::orderByDesc('is_active')->orderBy('code')->get();return view('human-capital.time.schedules.index',compact('patterns','assignments','overrides','employees','shifts'));}
    public function storePattern(SaveShiftPatternRequest $request):RedirectResponse{$this->gate('create');$data=$request->validated();if(ShiftPattern::where('code',$data['code'])->exists())throw ValidationException::withMessages(['code'=>'Pattern code already exists.']);$pattern=DB::transaction(function()use($request,$data){$p=ShiftPattern::create(['code'=>$data['code'],'name'=>$data['name'],'is_active'=>$request->boolean('is_active')]);$this->syncDays($p,$data['days']);return $p;});$this->audit->record('hr.schedules','create',$pattern,[],$pattern->toArray(),['type'=>'pattern']);return back()->with('success','Shift pattern created.');}
    public function updatePattern(SaveShiftPatternRequest $request,ShiftPattern $pattern):RedirectResponse{$this->gate('edit');$data=$request->validated();if(ShiftPattern::where('code',$data['code'])->where('id','!=',$pattern->id)->exists())throw ValidationException::withMessages(['code'=>'Pattern code already exists.']);$before=$pattern->load('days')->toArray();DB::transaction(function()use($request,$data,$pattern){$pattern->update(['code'=>$data['code'],'name'=>$data['name'],'is_active'=>$request->boolean('is_active')]);$this->syncDays($pattern,$data['days']);});$this->audit->record('hr.schedules','update',$pattern,$before,$pattern->fresh()->load('days')->toArray(),['type'=>'pattern']);return back()->with('success','Shift pattern updated.');}
    public function storeAssignment(SaveShiftAssignmentRequest $request):RedirectResponse{$this->gate('create');$d=$request->validated();$overlap=EmployeeShiftAssignment::where('employee_id',$d['employee_id'])->whereDate('effective_from','<=',($d['effective_to'] ?? null) ?: '9999-12-31')->where(fn($q)=>$q->whereNull('effective_to')->orWhereDate('effective_to','>=',$d['effective_from']))->exists();if($overlap)throw ValidationException::withMessages(['effective_from'=>'Schedule assignment overlaps another effective assignment.']);$d['created_by']=auth()->id();$d['updated_by']=auth()->id();$row=EmployeeShiftAssignment::create($d);$this->audit->record('hr.schedules','create',$row,[],$row->toArray(),['type'=>'assignment']);return back()->with('success','Employee schedule assigned.');}
    public function editAssignment(EmployeeShiftAssignment $assignment):View{$this->gate('edit');$employees=Employee::query()->where('is_active',true)->orWhereKey($assignment->employee_id)->orderBy('employee_code')->get();$patterns=ShiftPattern::query()->where('is_active',true)->orWhereKey($assignment->shift_pattern_id)->orderBy('code')->get();return view('human-capital.time.schedules.assignment-form',compact('assignment','employees','patterns'));}
    public function updateAssignment(SaveShiftAssignmentRequest $request,EmployeeShiftAssignment $assignment):RedirectResponse{$this->gate('edit');$d=$request->validated();$end=($d['effective_to'] ?? null) ?: '9999-12-31';$overlap=EmployeeShiftAssignment::where('employee_id',$d['employee_id'])->where('id','!=',$assignment->id)->whereDate('effective_from','<=',$end)->where(fn($q)=>$q->whereNull('effective_to')->orWhereDate('effective_to','>=',$d['effective_from']))->exists();if($overlap)throw ValidationException::withMessages(['effective_from'=>'Schedule assignment overlaps another effective assignment.']);$before=$assignment->toArray();$d['updated_by']=auth()->id();$assignment->update($d);$this->audit->record('hr.schedules','update',$assignment,$before,$assignment->fresh()->toArray(),['type'=>'assignment']);return redirect()->route('hr.schedules.index')->with('success','Schedule assignment updated.');}
    public function storeOverride(SaveScheduleOverrideRequest $request):RedirectResponse{$this->gate('edit');$d=$request->validated();$d['is_off']=$request->boolean('is_off');if(!$d['is_off']&&!$d['shift_id'])throw ValidationException::withMessages(['shift_id'=>'Select a Shift or mark the day OFF.']);if($d['is_off'])$d['shift_id']=null;$d['created_by']=auth()->id();$row=WorkScheduleOverride::updateOrCreate(['employee_id'=>$d['employee_id'],'work_date'=>$d['work_date']],$d);$this->audit->record('hr.schedules','update',$row,[],$row->toArray(),['type'=>'override']);return back()->with('success','Date override saved.');}
    private function syncDays(ShiftPattern $pattern,array $days):void{for($weekday=1;$weekday<=7;$weekday++){ $value=(string)($days[$weekday]??'OFF');$isOff=$value==='OFF';$shiftId=$isOff?null:(int)$value;if(!$isOff&&!Shift::whereKey($shiftId)->exists())throw new DomainException("Invalid shift for weekday {$weekday}.");ShiftPatternDay::updateOrCreate(['shift_pattern_id'=>$pattern->id,'weekday'=>$weekday],['shift_id'=>$shiftId,'is_off'=>$isOff]);}}
    private function gate(string $action):void{abort_unless($this->authz->allows(auth()->user(),'hr.schedules',$action),403);}
}
