@php
 $isEdit=$record->exists;
 $module=$module??'sales';
 $lines=old('lines',$prefill ?: ($record->relationLoaded('lines')?$record->lines->toArray():[]));
 $locationRows=$locations??collect();
@endphp
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-0">{{ $isEdit?'Edit':'New' }} {{ $title }}</h4>@if($isEdit)<span class="status-badge status-{{ $record->status }}">{{ $record->status }}</span>@endif</div><a class="btn btn-outline-secondary" href="{{ route($module.'.documents.index',$type) }}">Back</a></div>
<form method="post" action="{{ $isEdit?route($module.'.documents.update',[$type,$record->id]):route($module.'.documents.store',$type) }}">@csrf @if($isEdit)@method('PUT')@endif<input type="hidden" name="source_document_id" value="{{ old('source_document_id', request('source_id') ?: ($record->source_sales_request_id ?? $record->source_sales_order_id ?? $record->source_purchase_request_id ?? $record->source_purchase_order_id ?? null)) }}">
<div class="card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">{{ $module==='sales'?'Customer':'Vendor' }}</label><select class="form-select" name="{{ $module==='sales'?'customer_id':'vendor_id' }}" required><option value="">Select...</option>@foreach(($module==='sales'?$customers:$vendors) as $p)<option value="{{ $p->id }}" @selected((string)old($module==='sales'?'customer_id':'vendor_id',$module==='sales'?$record->customer_id:$record->vendor_id)===(string)$p->id)>{{ $p->code }} - {{ $p->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Document Date</label><input type="date" class="form-control" name="document_date" value="{{ old('document_date',optional($record->document_date)->format('Y-m-d') ?: now()->toDateString()) }}" required></div><div class="col-md-3"><label class="form-label">Location</label><select class="form-select" name="location_id"><option value="">-</option>@foreach($locationRows as $l)<option value="{{ $l->id }}" @selected((string)old('location_id',$record->location_id)===(string)$l->id)>{{ $l->code }} - {{ $l->name }}{{ $l->bin_mandatory?' (Bin Required)':'' }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Bin / Sub Location</label><select class="form-select" name="bin_id"><option value="">-</option>@foreach($locationRows as $l)@foreach($l->bins??[] as $b)<option value="{{ $b->id }}" @selected((string)old('bin_id',$record->bin_id)===(string)$b->id)>{{ $l->code }} / {{ $b->code }}</option>@endforeach @endforeach</select></div>@if($module==='sales'&&$type!=='shipment')<div class="col-md-4"><label class="form-label">Price Level</label><select class="form-select" name="price_level_id"><option value="">Customer Default</option>@foreach($priceLevels as $pl)<option value="{{ $pl->id }}" @selected((string)old('price_level_id',$record->price_level_id)===(string)$pl->id)>{{ $pl->sort_order }}. {{ $pl->code }} - {{ $pl->name }}</option>@endforeach</select><div class="form-text">Price is taken from approved effective Item Price.</div></div>@endif<div class="col-md-2"><label class="form-label">Currency</label><input class="form-control" name="currency_code" value="{{ old('currency_code',$record->currency_code ?: 'IDR') }}"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2">{{ old('notes',$record->notes) }}</textarea></div></div></div></div>
<div class="card"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Lines</strong><button type="button" id="add-line" class="btn btn-sm btn-outline-primary">+ Add Line</button></div><div class="table-responsive"><table class="table align-middle mb-0" id="lines-table"><thead><tr><th style="min-width:240px">Item</th><th style="width:120px">Qty</th>@if($module==='sales')<th style="width:150px">Manual Disc %</th>@else<th style="width:150px">Price</th>@endif<th style="width:150px">Cost</th><th style="width:100px">Tax %</th><th style="width:70px"></th></tr></thead><tbody></tbody></table></div><div class="card-body border-top"><button class="btn btn-primary">Save Document</button></div></div></form>
<template id="line-template"><tr><td><select class="form-select item-select" data-name="item_id" required><option value="">Select item...</option>@foreach($items as $i)<option value="{{ $i->id }}" data-type="{{ $i->item_type }}">{{ $i->code }} - {{ $i->name }} ({{ $i->item_type }})</option>@endforeach</select><input type="hidden" data-name="source_sales_request_line_id"><input type="hidden" data-name="source_sales_order_line_id"><input type="hidden" data-name="source_posted_shipment_line_id"><input type="hidden" data-name="source_purchase_request_line_id"><input type="hidden" data-name="source_purchase_order_line_id"><input type="hidden" data-name="source_posted_receipt_line_id"><input type="hidden" data-name="direct_service" value="0"></td><td><input class="form-control" type="number" step="0.0001" min="0.0001" data-name="quantity" required></td>@if($module==='sales')<td><input class="form-control" type="number" step="0.0001" min="0" max="100" data-name="manual_discount_pct" value="0"><div class="form-text">Location + Bin + Manual are sequential.</div></td>@else<td><input class="form-control" type="number" step="0.0001" min="0" data-name="unit_price" value="0"></td>@endif<td><input class="form-control" type="number" step="0.0001" min="0" data-name="unit_cost" value="0"></td><td><input class="form-control" type="number" step="0.0001" min="0" data-name="tax_rate" value="0"></td><td><button type="button" class="btn btn-sm btn-outline-danger remove-line">×</button></td></tr></template>
@push('scripts')<script>
(()=>{const tbody=document.querySelector('#lines-table tbody'),tpl=document.getElementById('line-template'),seed=@json(array_values($lines));let idx=0;function add(data={}){const tr=tpl.content.firstElementChild.cloneNode(true);tr.querySelectorAll('[data-name]').forEach(el=>{const n=el.dataset.name;el.name=`lines[${idx}][${n}]`;if(data[n]!==undefined&&data[n]!==null)el.value=data[n];});const sel=tr.querySelector('.item-select');if(data.item_id)sel.value=data.item_id;const opt=sel.options[sel.selectedIndex];if(opt&&opt.dataset.type&&opt.dataset.type!=='INVENTORY')tr.querySelector('[data-name="direct_service"]').value='1';sel.addEventListener('change',()=>{const o=sel.options[sel.selectedIndex];tr.querySelector('[data-name="direct_service"]').value=o?.dataset.type!=='INVENTORY'?'1':'0'});tr.querySelector('.remove-line').addEventListener('click',()=>tr.remove());tbody.appendChild(tr);idx++;}seed.length?seed.forEach(add):add();document.getElementById('add-line').addEventListener('click',()=>add());})();
</script>@endpush
