<!doctype html>
<html><head><meta charset="utf-8"><style>
@page{margin:20px 24px}body{font-family:"DejaVu Sans",sans-serif;font-size:9px;color:#1f2937}h1{font-size:16px;margin:0 0 3px}h2{font-size:11px;margin:0;color:#52627a}.meta{margin:12px 0 14px;border-top:1px solid #d8dee8;border-bottom:1px solid #d8dee8;padding:7px 0}.meta div{margin:2px 0}.filters{margin-bottom:10px}.filters span{display:inline-block;border:1px solid #d8dee8;border-radius:4px;padding:3px 5px;margin:0 3px 3px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #d8dee8;padding:4px 5px;vertical-align:top}th{background:#eef2f7;text-align:left}.num{text-align:right}.totals th{background:#e7ebf1}.notes{margin-top:10px;padding:6px;border:1px solid #e3c36a;background:#fff8db}.footer{margin-top:10px;font-size:8px;color:#6b7280}
</style></head><body>
<h1>CGOne ERP · {{ $definition->name }}</h1>
<h2>{{ $definition->category }} · {{ $definition->report_type }}</h2>
<div class="meta">
<div><strong>Database:</strong> {{ $databaseName }}</div>
<div><strong>Generated By:</strong> {{ $user->name }}</div>
<div><strong>Generated At:</strong> {{ now()->format('d/m/Y H:i:s') }}</div>
</div>
@if($parameters)
<div class="filters"><strong>Filters:</strong><br>
@foreach($parameters as $key=>$value)<span>{{ ucwords(str_replace('_',' ',$key)) }}: {{ $value===null||$value===''?'ALL':$value }}</span>@endforeach
</div>
@endif
@if($result->summary)
<div class="filters"><strong>Summary:</strong><br>
@foreach($result->summary as $key=>$value)<span>{{ $key }}: {{ is_numeric($value)?number_format((float)$value,2,',','.'):$value }}</span>@endforeach
</div>
@endif
<table><thead><tr>@foreach($result->columns as $column)<th class="{{ in_array($column->type,['money','number','quantity','percent'],true)?'num':'' }}">{{ $column->label }}</th>@endforeach</tr></thead>
<tbody>@forelse($result->rows as $row)<tr>@foreach($result->columns as $column)@php $v=$result->value($row,$column->key); @endphp<td class="{{ in_array($column->type,['money','number','quantity','percent'],true)?'num':'' }}">@if(is_numeric($v) && in_array($column->type,['money','number','quantity','percent'],true)){{ number_format((float)$v,$column->decimals,',','.') }}@else{{ $v===null||$v===''?'-':$v }}@endif</td>@endforeach</tr>@empty<tr><td colspan="{{ max(1,count($result->columns)) }}">No data for selected filters.</td></tr>@endforelse</tbody>
@if($result->totals)<tfoot class="totals"><tr>@foreach($result->columns as $i=>$column)<th class="{{ in_array($column->type,['money','number','quantity','percent'],true)?'num':'' }}">@if($i===0)GRAND TOTAL @elseif(array_key_exists($column->key,$result->totals))@php $v=$result->totals[$column->key]; @endphp{{ is_numeric($v)?number_format((float)$v,$column->decimals,',','.'):$v }}@endif</th>@endforeach</tr></tfoot>@endif
</table>
@if($result->notes)<div class="notes">@foreach($result->notes as $note)<div>{{ $note }}</div>@endforeach</div>@endif
<div class="footer">Rows: {{ number_format($result->rowCount(),0,',','.') }} · Business Unit is a record dimension/filter and is not applied implicitly.</div>
</body></html>
