<?php
namespace App\Services\Adjustment;
use App\Models\{Adjustment,CustomerLedger,GlBatch,ItemLedger,User,VendorLedger}; use App\Services\Audit\ActivityLogService; use App\Services\Ledger\{CustomerLedgerService,GeneralLedgerService,ItemLedgerService,VendorLedgerService}; use App\Services\System\DocumentSequenceService; use DomainException; use Illuminate\Support\Facades\DB;
class AdjustmentService {
 public function __construct(private DocumentSequenceService $sequence,private ItemLedgerService $items,private CustomerLedgerService $customers,private VendorLedgerService $vendors,private GeneralLedgerService $gl,private ActivityLogService $audit){}
 public function reverse(string $ledgerType,int $sourceId,string $reason,User $user): Adjustment { if(mb_strlen(trim($reason))<10)throw new DomainException('Adjustment reason must be at least 10 characters.');if(!in_array($ledgerType,['item','customer','vendor','gl'],true))throw new DomainException('Unsupported ledger type.');return DB::transaction(function() use($ledgerType,$sourceId,$reason,$user){if(Adjustment::where('ledger_type',$ledgerType)->where('source_entry_id',$sourceId)->exists())throw new DomainException('This posted entry has already been reversed.');$doc=$this->sequence->next('ADJ');$reversalId=match($ledgerType){'item'=>$this->reverseItem($sourceId,$doc,$user),'customer'=>$this->reverseCustomer($sourceId,$doc,$user),'vendor'=>$this->reverseVendor($sourceId,$doc,$user),'gl'=>$this->reverseGl($sourceId,$doc,$user)};$adj=Adjustment::create(['document_number'=>$doc,'ledger_type'=>$ledgerType,'source_entry_id'=>$sourceId,'reversal_entry_id'=>$reversalId,'reason'=>$reason,'requested_by'=>$user->id,'approved_by'=>$user->id,'posted_at'=>now()]);$this->audit->record('transactions.adjustment','reverse',$adj,[], $adj->toArray(),['document_number'=>$doc,'ledger_type'=>$ledgerType,'source_entry_id'=>$sourceId,'reversal_entry_id'=>$reversalId,'reason'=>$reason]);return $adj;}); }
 private function reverseItem(int $id,string $doc,User $user): int {$s=ItemLedger::findOrFail($id);$r=$this->items->post(['posting_at'=>now(),'source_module'=>'ADJUSTMENT','document_type'=>'REVERSAL','document_number'=>$doc,'item_id'=>$s->item_id,'warehouse_id'=>$s->warehouse_id,'location_id'=>$s->location_id,'bin_id'=>$s->bin_id,'qty_in'=>$s->qty_out,'qty_out'=>$s->qty_in,'unit_cost'=>$s->unit_cost,'amount'=>(float)$s->amount*-1,'description'=>'Reversal of '.$s->document_number,'posted_by'=>$user->id,'reversal_of_id'=>$s->id]);return $r->id;}
 private function reverseCustomer(int $id,string $doc,User $user): int {$s=CustomerLedger::findOrFail($id);$r=$this->customers->post(['posting_at'=>now(),'source_module'=>'ADJUSTMENT','document_type'=>'REVERSAL','document_number'=>$doc,'customer_id'=>$s->customer_id,'debit'=>$s->credit,'credit'=>$s->debit,'description'=>'Reversal of '.$s->document_number,'posted_by'=>$user->id,'reversal_of_id'=>$s->id]);return $r->id;}
 private function reverseVendor(int $id,string $doc,User $user): int {$s=VendorLedger::findOrFail($id);$r=$this->vendors->post(['posting_at'=>now(),'source_module'=>'ADJUSTMENT','document_type'=>'REVERSAL','document_number'=>$doc,'vendor_id'=>$s->vendor_id,'debit'=>$s->credit,'credit'=>$s->debit,'description'=>'Reversal of '.$s->document_number,'posted_by'=>$user->id,'reversal_of_id'=>$s->id]);return $r->id;}
 private function reverseGl(int $id,string $doc,User $user): int {$s=GlBatch::with('entries')->findOrFail($id);$lines=$s->entries->map(fn($line)=>['account_id'=>$line->account_id,'debit'=>$line->credit,'credit'=>$line->debit,'description'=>'Reversal of '.$s->document_number,'reversal_of_id'=>$line->id])->all();$r=$this->gl->postBatch(['document_number'=>$doc,'posting_at'=>now(),'source_module'=>'ADJUSTMENT','document_type'=>'REVERSAL','description'=>'Reversal of '.$s->document_number,'posted_by'=>$user->id,'reversal_of_id'=>$s->id],$lines);return $r->id;}
}
