<?php
namespace App\Reports\Standard;
use App\Services\Reports\Contracts\StandardReport;use App\Services\Reports\ReportDataRequirementService;use App\Services\Reports\ReportResult;use Carbon\CarbonImmutable;use Illuminate\Support\Facades\DB;
final class CustomerAgingReport extends AbstractStandardReport implements StandardReport{
 public function __construct(private readonly ReportDataRequirementService $requirements){}public function code():string{return 'CUSTOMER_AGING';}
 public function parameters():array{return array_merge($this->asOfParameters(),['customer_id'=>$this->lookupParameter('Customer','customers')]);}
 public function run(array $parameters):ReportResult{if(!$this->requirements->customerAgingReady($parameters))return new ReportResult('Customer Aging',[$this->col('customer_code','Customer'),$this->col('current','Current','money'),$this->col('d1_30','1-30','money'),$this->col('d31_60','31-60','money'),$this->col('d61_90','61-90','money'),$this->col('over_90','>90','money'),$this->col('total','Total','money')],[],notes:['Aging belum dapat dihitung secara aman untuk filter ini. Pastikan seluruh invoice memiliki Due Date dan setiap pembayaran/credit sudah diaplikasikan ke invoice melalui ledger application. Sistem tidak menggunakan Last Posting Date sebagai pengganti Due Date.']);
  $asOf=CarbonImmutable::parse($parameters['as_of']);$apps=DB::table('customer_ledger_applications')->select('target_debit_ledger_id')->selectRaw('SUM(applied_amount) AS applied_amount')->where('applied_at','<',$asOf->addDay()->startOfDay())->groupBy('target_debit_ledger_id');
  $q=DB::table('posted_sales_invoices as p')->join('customers as c','c.id','=','p.customer_id')->leftJoin('business_units as bu','bu.id','=','p.business_unit_id')->leftJoinSub($apps,'a',fn($j)=>$j->on('a.target_debit_ledger_id','=','p.customer_ledger_id'))->leftJoin('posted_document_undos as u',function($j){$j->on('u.posted_id','=','p.id')->where('u.posted_type','=','PostedSalesInvoice');})->whereNull('u.id')->where('p.document_date','<=',$parameters['as_of']);
  if(!empty($parameters['customer_id']))$q->where('p.customer_id',(int)$parameters['customer_id']);if(!empty($parameters['business_unit_id']))$q->where('p.business_unit_id',(int)$parameters['business_unit_id']);
  $invoices=$q->select('c.code as customer_code','c.name as customer_name','bu.code as business_unit','p.document_no','p.due_date','p.grand_total',DB::raw('COALESCE(a.applied_amount,0) AS applied_amount'))->orderBy('c.code')->orderBy('p.due_date')->get();$group=[];
  foreach($invoices as $inv){$out=max(0,(float)$inv->grand_total-(float)$inv->applied_amount);if($out<=0.0001)continue;$key=$inv->customer_code.'|'.($inv->business_unit??'');$group[$key]??=['customer_code'=>$inv->customer_code,'customer_name'=>$inv->customer_name,'business_unit'=>$inv->business_unit,'current'=>0.0,'d1_30'=>0.0,'d31_60'=>0.0,'d61_90'=>0.0,'over_90'=>0.0,'total'=>0.0];$due=CarbonImmutable::parse($inv->due_date);$days=$due->gte($asOf)?0:$due->diffInDays($asOf);$bucket=$days===0?'current':($days<=30?'d1_30':($days<=60?'d31_60':($days<=90?'d61_90':'over_90')));$group[$key][$bucket]+=$out;$group[$key]['total']+=$out;}
  $rows=array_values($group);usort($rows,fn($a,$b)=>[$a['customer_code'],$a['business_unit']]<=>[$b['customer_code'],$b['business_unit']]);return new ReportResult('Customer Aging',[$this->col('customer_code','Customer'),$this->col('customer_name','Name'),$this->col('business_unit','Business Unit'),$this->col('current','Current','money'),$this->col('d1_30','1-30','money'),$this->col('d31_60','31-60','money'),$this->col('d61_90','61-90','money'),$this->col('over_90','>90','money'),$this->col('total','Total','money')],$rows,['Outstanding'=>$this->moneySum($rows,'total')],['current'=>$this->moneySum($rows,'current'),'d1_30'=>$this->moneySum($rows,'d1_30'),'d31_60'=>$this->moneySum($rows,'d31_60'),'d61_90'=>$this->moneySum($rows,'d61_90'),'over_90'=>$this->moneySum($rows,'over_90'),'total'=>$this->moneySum($rows,'total')]);}
}
