<?php
namespace App\Reports\Standard;
use App\Models\Documents\PurchaseOrder;use App\Services\Documents\PartialQuantityService;use App\Services\Reports\Contracts\StandardReport;use App\Services\Reports\ReportResult;use Carbon\CarbonImmutable;
final class PurchaseOutstandingOrdersReport extends AbstractStandardReport implements StandardReport{
 public function __construct(private readonly PartialQuantityService $partial){}public function code():string{return 'PURCHASE_OUTSTANDING_ORDERS';}
 public function parameters():array{return array_merge($this->periodParameters(),['as_of'=>['label'=>'As Of','type'=>'date','default'=>now()->toDateString()],'vendor_id'=>$this->lookupParameter('Vendor','vendors'),'location_id'=>$this->lookupParameter('Location','locations')]);}
 public function run(array $p):ReportResult{$q=PurchaseOrder::query()->with(['vendor','lines.item','businessUnit','location'])->where('status','RELEASED');$this->applyDatePeriod($q,'document_date',$p);$this->applyBusinessUnit($q,'business_unit_id',$p);if(!empty($p['vendor_id']))$q->where('vendor_id',(int)$p['vendor_id']);if(!empty($p['location_id']))$q->where('location_id',(int)$p['location_id']);$asOf=CarbonImmutable::parse($p['as_of']);$rows=[];foreach($q->orderBy('document_date')->orderBy('id')->get() as $order){foreach($order->lines as $line){$remaining=(float)$this->partial->remainingPurchaseOrderLine($line);if($remaining<=0)continue;$ordered=(float)$line->quantity;$rows[]=['document_no'=>$order->document_no,'document_date'=>$order->document_date?->format('Y-m-d'),'age_days'=>max(0,CarbonImmutable::parse($order->document_date)->diffInDays($asOf,false)),'business_unit'=>$order->businessUnit?->code,'location'=>$order->location?->code,'vendor'=>$order->vendor?->code.' - '.$order->vendor?->name,'item'=>$line->item?->code,'ordered'=>$ordered,'received'=>max(0,$ordered-$remaining),'remaining'=>$remaining];if(count($rows)>=(int)config('reports.screen_row_limit',5000))break 2;}}
  return new ReportResult('Outstanding Purchase Orders',[$this->col('document_no','Purchase Order'),$this->col('document_date','Date','date'),$this->col('age_days','Age Days','number',0),$this->col('business_unit','Business Unit'),$this->col('location','Location'),$this->col('vendor','Vendor'),$this->col('item','Item'),$this->col('ordered','Ordered','quantity',4),$this->col('received','Received','quantity',4),$this->col('remaining','Remaining','quantity',4)],$rows,[],['ordered'=>$this->qtySum($rows,'ordered'),'received'=>$this->qtySum($rows,'received'),'remaining'=>$this->qtySum($rows,'remaining')]);}
}
