<?php
namespace App\Reports\Standard;
use App\Models\Documents\PostedReceipt;use App\Services\Documents\PartialQuantityService;use App\Services\Reports\Contracts\StandardReport;use App\Services\Reports\ReportResult;use Carbon\CarbonImmutable;
final class PurchaseOutstandingReceiptsReport extends AbstractStandardReport implements StandardReport{
 public function __construct(private readonly PartialQuantityService $partial){}public function code():string{return 'PURCHASE_OUTSTANDING_RECEIPTS';}
 public function parameters():array{return array_merge($this->periodParameters(),['as_of'=>['label'=>'As Of','type'=>'date','default'=>now()->toDateString()],'vendor_id'=>$this->lookupParameter('Vendor','vendors'),'location_id'=>$this->lookupParameter('Location','locations')]);}
 public function run(array $p):ReportResult{$q=PostedReceipt::query()->with(['vendor','lines.item','undo','location']);$this->applyDatePeriod($q,'document_date',$p);$this->applyBusinessUnit($q,'business_unit_id',$p);if(!empty($p['vendor_id']))$q->where('vendor_id',(int)$p['vendor_id']);if(!empty($p['location_id']))$q->where('location_id',(int)$p['location_id']);$bu=$this->businessUnitCodeMap();$asOf=CarbonImmutable::parse($p['as_of']);$rows=[];foreach($q->orderBy('document_date')->orderBy('id')->get() as $doc){if($doc->effectiveStatus()!=='POSTED')continue;foreach($doc->lines as $line){$remaining=(float)$this->partial->remainingPostedReceiptLine($line->id,(float)$line->quantity);if($remaining<=0)continue;$received=(float)$line->quantity;$rows[]=['document_no'=>$doc->document_no,'document_date'=>$doc->document_date?->format('Y-m-d'),'age_days'=>max(0,CarbonImmutable::parse($doc->document_date)->diffInDays($asOf,false)),'business_unit'=>$bu[$doc->business_unit_id]??null,'location'=>$doc->location?->code,'vendor'=>$doc->vendor?->code.' - '.$doc->vendor?->name,'item'=>$line->item_code,'received'=>$received,'invoiced'=>max(0,$received-$remaining),'uninvoiced'=>$remaining];if(count($rows)>=(int)config('reports.screen_row_limit',5000))break 2;}}
  return new ReportResult('Receipt Not Invoiced',[$this->col('document_no','Posted Receipt'),$this->col('document_date','Date','date'),$this->col('age_days','Age Days','number',0),$this->col('business_unit','Business Unit'),$this->col('location','Location'),$this->col('vendor','Vendor'),$this->col('item','Item'),$this->col('received','Received','quantity',4),$this->col('invoiced','Invoiced','quantity',4),$this->col('uninvoiced','Uninvoiced','quantity',4)],$rows,[],['received'=>$this->qtySum($rows,'received'),'invoiced'=>$this->qtySum($rows,'invoiced'),'uninvoiced'=>$this->qtySum($rows,'uninvoiced')]);}
}
