<?php
namespace App\Reports\Standard;
use App\Models\Documents\PostedShipment;use App\Services\Documents\PartialQuantityService;use App\Services\Reports\Contracts\StandardReport;use App\Services\Reports\ReportResult;use Carbon\CarbonImmutable;
final class SalesOutstandingShipmentsReport extends AbstractStandardReport implements StandardReport{
 public function __construct(private readonly PartialQuantityService $partial){}public function code():string{return 'SALES_OUTSTANDING_SHIPMENTS';}
 public function parameters():array{return array_merge($this->periodParameters(),['as_of'=>['label'=>'As Of','type'=>'date','default'=>now()->toDateString()],'customer_id'=>$this->lookupParameter('Customer','customers'),'location_id'=>$this->lookupParameter('Location','locations')]);}
 public function run(array $p):ReportResult{$q=PostedShipment::query()->with(['customer','lines.item','undo','location']);$this->applyDatePeriod($q,'document_date',$p);$this->applyBusinessUnit($q,'business_unit_id',$p);if(!empty($p['customer_id']))$q->where('customer_id',(int)$p['customer_id']);if(!empty($p['location_id']))$q->where('location_id',(int)$p['location_id']);$bu=$this->businessUnitCodeMap();$asOf=CarbonImmutable::parse($p['as_of']);$rows=[];foreach($q->orderBy('document_date')->orderBy('id')->get() as $doc){if($doc->effectiveStatus()!=='POSTED')continue;foreach($doc->lines as $line){$remaining=(float)$this->partial->remainingPostedShipmentLine($line->id,(float)$line->quantity);if($remaining<=0)continue;$shipped=(float)$line->quantity;$rows[]=['document_no'=>$doc->document_no,'document_date'=>$doc->document_date?->format('Y-m-d'),'age_days'=>max(0,CarbonImmutable::parse($doc->document_date)->diffInDays($asOf,false)),'business_unit'=>$bu[$doc->business_unit_id]??null,'location'=>$doc->location?->code,'customer'=>$doc->customer?->code.' - '.$doc->customer?->name,'item'=>$line->item_code,'shipped'=>$shipped,'invoiced'=>max(0,$shipped-$remaining),'uninvoiced'=>$remaining];if(count($rows)>=(int)config('reports.screen_row_limit',5000))break 2;}}
  return new ReportResult('Shipment Not Invoiced',[$this->col('document_no','Posted Shipment'),$this->col('document_date','Date','date'),$this->col('age_days','Age Days','number',0),$this->col('business_unit','Business Unit'),$this->col('location','Location'),$this->col('customer','Customer'),$this->col('item','Item'),$this->col('shipped','Shipped','quantity',4),$this->col('invoiced','Invoiced','quantity',4),$this->col('uninvoiced','Uninvoiced','quantity',4)],$rows,[],['shipped'=>$this->qtySum($rows,'shipped'),'invoiced'=>$this->qtySum($rows,'invoiced'),'uninvoiced'=>$this->qtySum($rows,'uninvoiced')]);}
}
