<?php
namespace App\Reports\Standard;
use App\Models\Documents\SalesOrder;use App\Services\Documents\PartialQuantityService;use App\Services\Reports\Contracts\StandardReport;use App\Services\Reports\ReportResult;use Carbon\CarbonImmutable;
final class SalesOutstandingOrdersReport extends AbstractStandardReport implements StandardReport{
 public function __construct(private readonly PartialQuantityService $partial){}public function code():string{return 'SALES_OUTSTANDING_ORDERS';}
 public function parameters():array{return array_merge($this->periodParameters(),['as_of'=>['label'=>'As Of','type'=>'date','default'=>now()->toDateString()],'customer_id'=>$this->lookupParameter('Customer','customers'),'location_id'=>$this->lookupParameter('Location','locations')]);}
 public function run(array $p):ReportResult{$q=SalesOrder::query()->with(['customer','lines.item','businessUnit','location'])->where('status','RELEASED');$this->applyDatePeriod($q,'document_date',$p);$this->applyBusinessUnit($q,'business_unit_id',$p);if(!empty($p['customer_id']))$q->where('customer_id',(int)$p['customer_id']);if(!empty($p['location_id']))$q->where('location_id',(int)$p['location_id']);$asOf=CarbonImmutable::parse($p['as_of']);$rows=[];foreach($q->orderBy('document_date')->orderBy('id')->get() as $order){foreach($order->lines as $line){$remaining=(float)$this->partial->remainingSalesOrderLine($line);if($remaining<=0)continue;$ordered=(float)$line->quantity;$rows[]=['document_no'=>$order->document_no,'document_date'=>$order->document_date?->format('Y-m-d'),'business_unit'=>$order->businessUnit?->code,'location'=>$order->location?->code,'customer'=>$order->customer?->code.' - '.$order->customer?->name,'item'=>$line->item?->code,'ordered'=>$ordered,'shipped'=>max(0,$ordered-$remaining),'remaining'=>$remaining,'age_days'=>max(0,CarbonImmutable::parse($order->document_date)->diffInDays($asOf,false))];if(count($rows)>=(int)config('reports.screen_row_limit',5000))break 2;}}
  return new ReportResult('Outstanding Sales Orders',[$this->col('document_no','Sales Order'),$this->col('document_date','Date','date'),$this->col('age_days','Age Days','number',0),$this->col('business_unit','Business Unit'),$this->col('location','Location'),$this->col('customer','Customer'),$this->col('item','Item'),$this->col('ordered','Ordered','quantity',4),$this->col('shipped','Shipped','quantity',4),$this->col('remaining','Remaining','quantity',4)],$rows,[],['ordered'=>$this->qtySum($rows,'ordered'),'shipped'=>$this->qtySum($rows,'shipped'),'remaining'=>$this->qtySum($rows,'remaining')]);}
}
