@extends('layouts.app')
@section('title',$batch->batch_no)
@section('content')
@php
    $authz = app(\App\Services\Security\MenuAuthorizationService::class);
@endphp
<div class="d-flex justify-content-between mb-3 gap-2 flex-wrap"><div><h4 class="mb-0">{{ $batch->batch_no }}</h4><span class="status-badge status-{{ $batch->status }}">{{ $batch->status }}</span><div class="text-muted">{{ $batch->description }}</div></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('price-approval.index',['batch_id'=>$batch->id,'approval_status'=>'PENDING']) }}">Open Price Approval</a><a class="btn btn-outline-secondary" href="{{ route('price-updates.index') }}">Back</a></div></div>
@if($batch->status==='RELEASED')<div class="alert alert-warning"><strong>PRICE HOLD ACTIVE:</strong> items with <code>approval_status = PENDING</code> are disabled for transaction processing. An item is unlocked immediately after all of its lines in this batch are Approved or Rejected, unless another released price batch for that item is still pending.</div>@endif
<div class="card mb-3"><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Item</th><th>Price Level</th><th>UOM</th><th class="text-end">Old Price</th><th class="text-end">New Price</th><th>Effective</th><th>Change</th><th>Approval</th></tr></thead><tbody>@foreach($batch->lines as $l)@php $pct=$l->old_price&&$l->old_price>0?(((float)$l->new_price-(float)$l->old_price)/(float)$l->old_price*100):null; @endphp<tr><td>{{ $l->item?->code }} - {{ $l->item?->name }}</td><td>{{ $l->priceLevel?->code }}</td><td>{{ $l->uom?->code }}</td><td class="text-end">{{ $l->old_price===null?'-':number_format((float)$l->old_price,2,',','.') }}</td><td class="text-end fw-bold">{{ number_format((float)$l->new_price,2,',','.') }}</td><td>{{ $l->effective_date?->format('Y-m-d') }}</td><td>{{ $pct===null?'-':number_format($pct,2).'%' }}</td><td>@if($l->approval_status==='APPROVED')<span class="badge text-bg-success">APPROVED</span>@elseif($l->approval_status==='REJECTED')<span class="badge text-bg-danger">REJECTED</span>@else<span class="badge text-bg-warning">PENDING</span>@endif @if($l->rejection_reason)<div class="small text-danger">{{ $l->rejection_reason }}</div>@endif</td></tr>@endforeach</tbody></table></div></div>
<div class="d-flex gap-2 flex-wrap">@if($batch->status==='OPEN'&&$authz->allows(auth()->user(),'pricing.price-updates','release'))<form method="post" action="{{ route('price-updates.release',$batch) }}">@csrf<button class="btn btn-warning">Release & Lock Items</button></form>@endif @if($batch->status==='RELEASED'&&$authz->allows(auth()->user(),'pricing.price-approval','approve'))<a class="btn btn-success" href="{{ route('price-approval.index',['batch_id'=>$batch->id,'approval_status'=>'PENDING']) }}">Review Pending Prices</a>@endif</div>
@endsection
