<?php
namespace App\Http\Controllers\Pricing;
use App\Http\Controllers\Controller;
use App\Models\{Item,PriceLevel,Uom};
use App\Models\Pricing\{PriceUpdateBatch,PriceUpdateLine};
use App\Services\Pricing\{ItemPriceService,PriceUpdateApprovalService,SimpleXlsxReader};
use App\Services\Audit\ActivityLogService;
use App\Services\System\DocumentSequenceService;
use Carbon\Carbon; use DomainException; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class PriceUpdateController extends Controller {
 public function __construct(private SimpleXlsxReader $xlsx,private ItemPriceService $prices,private PriceUpdateApprovalService $approval,private DocumentSequenceService $numbers,private ActivityLogService $audit){}
 private function gate(Request $r,string $p): void {abort_unless(app(\App\Services\Security\MenuAuthorizationService::class)->allows($r->user(),'pricing.price-updates',$p),403);}
 public function index(Request $r){$this->gate($r,'view');$q=PriceUpdateBatch::withCount(['lines','lines as pending_lines_count'=>fn($x)=>$x->where('approval_status','PENDING'),'lines as approved_lines_count'=>fn($x)=>$x->where('approval_status','APPROVED'),'lines as rejected_lines_count'=>fn($x)=>$x->where('approval_status','REJECTED')])->latest('id');if($r->filled('status'))$q->where('status',$r->input('status'));return view('pricing.price-updates.index',['rows'=>$q->paginate(30)->withQueryString()]);}
 public function template(Request $r){$this->gate($r,'view');$path=storage_path('app/templates/price-level-update-template.xlsx');abort_unless(is_file($path),404,'Template not installed.');return response()->download($path,'price-level-update-template.xlsx');}
 public function import(Request $r){$this->gate($r,'create');$v=$r->validate(['description'=>'required|string|max:255','file'=>'required|file|mimes:xlsx|max:10240']);$rows=$this->xlsx->rows($r->file('file')->getRealPath());if(!$rows)throw new DomainException('Excel contains no data.');$prepared=[];$errors=[];$seen=[];foreach($rows as $i=>$row){$line=$i+2;$item=Item::where('code',trim((string)($row['Item Code']??'')))->first();$level=PriceLevel::where('code',trim((string)($row['Price Level']??'')))->where('is_active',true)->first();$uom=Uom::where('code',trim((string)($row['UOM']??'')))->where('is_active',true)->first();$new=(float)($row['New Price']??0);try{$date=$this->dateValue($row['Effective Date']??null);}catch(\Throwable){$date=null;}if(!$item)$errors[]="Row {$line}: Item Code not found.";elseif(!$level)$errors[]="Row {$line}: Price Level not found.";elseif(!$uom)$errors[]="Row {$line}: UOM not found.";elseif((int)$item->base_uom_id!==(int)$uom->id && !$item->uoms()->where('uom_id',$uom->id)->exists())$errors[]="Row {$line}: UOM is not assigned to item {$item->code}.";elseif($new<=0)$errors[]="Row {$line}: New Price must be greater than zero.";elseif(!$date)$errors[]="Row {$line}: Effective Date is invalid.";else{$dupKey=$item->id.'|'.$level->id.'|'.$uom->id;if(isset($seen[$dupKey])){$errors[]="Row {$line}: duplicate Item / Price Level / UOM in this file.";continue;}$seen[$dupKey]=true;$old=null;try{$old=(float)$this->prices->effectivePrice($item,$level,$uom,$date)->price;}catch(\Throwable){}$prepared[]=['item_id'=>$item->id,'price_level_id'=>$level->id,'uom_id'=>$uom->id,'old_price'=>$old,'new_price'=>$new,'effective_date'=>$date->toDateString(),'validation_status'=>'VALID','notes'=>$row['Notes']??null];}}if($errors)return back()->withErrors($errors);$batch=DB::transaction(function()use($v,$prepared,$r){$batch=PriceUpdateBatch::create(['batch_no'=>$this->numbers->next('PRICE_UPDATE_BATCH'),'description'=>$v['description'],'status'=>'OPEN','uploaded_by'=>$r->user()->id,'source_filename'=>$r->file('file')->getClientOriginalName()]);foreach($prepared as $line)$batch->lines()->create($line);return$batch;});$this->audit->record('pricing.price-updates','import',$batch,[],$batch->fresh()->toArray(),['document_number'=>$batch->batch_no,'source_filename'=>$batch->source_filename]);return redirect()->route('price-updates.show',$batch)->with('success','Excel validated. Review and Release for approval.');}
 public function show(Request $r,PriceUpdateBatch $batch){$this->gate($r,'view');$batch->load(['lines.item','lines.priceLevel','lines.uom']);return view('pricing.price-updates.show',['batch'=>$batch]);}
 public function release(Request $r,PriceUpdateBatch $batch){$this->gate($r,'release');$before=$batch->toArray();$this->approval->release($batch,(int)$r->user()->id);$fresh=$batch->fresh();$this->audit->record('pricing.price-updates','release',$fresh,$before,$fresh->toArray(),['document_number'=>$fresh->batch_no]);return back()->with('success','Batch released. Affected items are now locked until approval/rejection.');}
 public function approve(Request $r,PriceUpdateBatch $batch){$this->gate($r,'approve');abort_if((int)$batch->uploaded_by===(int)$r->user()->id,422,'Uploader cannot approve their own price update.');$before=$batch->toArray();$this->approval->approve($batch,(int)$r->user()->id);$fresh=$batch->fresh();$this->audit->record('pricing.price-updates','approve',$fresh,$before,$fresh->toArray(),['document_number'=>$fresh->batch_no]);return back()->with('success','Price update approved and effective-dated prices created.');}
 public function reject(Request $r,PriceUpdateBatch $batch){$this->gate($r,'approve');$reason=$r->validate(['reason'=>'required|string|max:1000'])['reason'];$before=$batch->toArray();$this->approval->reject($batch,(int)$r->user()->id,$reason);$fresh=$batch->fresh();$this->audit->record('pricing.price-updates','reject',$fresh,$before,$fresh->toArray(),['document_number'=>$fresh->batch_no,'reason'=>$reason]);return back()->with('success','Price update rejected. Item price locks were released.');}
 private function dateValue(mixed $v): ?Carbon {if($v===null||$v==='')return null;if(is_numeric($v)&&(float)$v>20000)return Carbon::create(1899,12,30)->addDays((int)$v);return Carbon::parse((string)$v);}
}
