@extends('layouts.app')
@section('title',$definition->name)
@section('content')
@php
    $databaseName = \Illuminate\Support\Facades\DB::connection()->getDatabaseName();
    $sensitiveParameterKeys = collect($schema ?? [])->filter(fn($config)=>(bool)($config['sensitive'] ?? false))->keys()->all();
    $exportParams = array_filter($parameters, fn($v,$k)=>$v!==null && $v!=='' && !in_array($k,$sensitiveParameterKeys,true), ARRAY_FILTER_USE_BOTH);
    if($selectedView) $exportParams['view_id']=$selectedView->id;
@endphp
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3">
    <div>
        <div class="text-muted small">{{ $definition->category }} · {{ $definition->report_type }}</div>
        <h3 class="mb-1">{{ $definition->name }}</h3>
        <div class="small text-muted">Database: <strong>{{ $databaseName }}</strong> · Generated by {{ auth()->user()->name }} · {{ now()->format('d/m/Y H:i') }}</div>
    </div>
    <div class="d-flex gap-2 flex-wrap">
        <a class="btn btn-light" href="{{ route('reports.center') }}">Report Center</a>
        @if($definition->report_type===\App\Models\Reports\ReportDefinition::TYPE_VISUAL && $permissions->allows('edit'))
            <a class="btn btn-outline-primary" href="{{ route('reports.builder.edit',$definition) }}">Edit Report</a>
        @elseif($definition->report_type===\App\Models\Reports\ReportDefinition::TYPE_SQL && $permissions->allows('edit'))
            <a class="btn btn-outline-primary" href="{{ route('reports.sql.edit',$definition) }}">Edit SQL Report</a>
        @endif
        @if($permissions->allows('share'))
            <a class="btn btn-outline-secondary" href="{{ route('reports.access.edit',$definition) }}">Share / Access</a>
        @endif
        @if(in_array($definition->report_type,[\App\Models\Reports\ReportDefinition::TYPE_VISUAL,\App\Models\Reports\ReportDefinition::TYPE_SQL],true) && $permissions->allows('clone'))
            <form method="post" action="{{ route('reports.clone',$definition) }}">@csrf<button class="btn btn-outline-secondary">Clone</button></form>
        @endif
        @if(in_array($definition->report_type,[\App\Models\Reports\ReportDefinition::TYPE_VISUAL,\App\Models\Reports\ReportDefinition::TYPE_SQL],true) && ($permissions->allows('edit') || $permissions->allows('manage')))
            <a class="btn btn-outline-secondary" href="{{ route('reports.versions.index',$definition) }}">Versions</a>
        @endif
        @if($permissions->allows('export'))
            <a class="btn btn-outline-success" href="{{ route('reports.export',array_merge(['report'=>$definition,'format'=>'xlsx'],$exportParams)) }}">Excel</a>
            <a class="btn btn-outline-secondary" href="{{ route('reports.export',array_merge(['report'=>$definition,'format'=>'csv'],$exportParams)) }}">CSV</a>
            <a class="btn btn-outline-danger" href="{{ route('reports.export',array_merge(['report'=>$definition,'format'=>'pdf'],$exportParams)) }}">PDF</a>
        @endif
        @if($permissions->allows('print'))
            <a class="btn btn-outline-secondary" target="_blank" href="{{ route('reports.print',array_merge(['report'=>$definition],$exportParams)) }}">Print</a>
        @endif
    </div>
</div>

@if(!empty($schema))
<div class="card mb-3">
    <div class="card-header bg-white d-flex justify-content-between align-items-center">
        <strong>Filters</strong>
        <button class="btn btn-sm btn-light" type="button" data-bs-toggle="collapse" data-bs-target="#reportFilters">Show / Hide</button>
    </div>
    <div class="collapse show" id="reportFilters"><div class="card-body">
        @include('reports.partials.filters')
    </div></div>
</div>

<div class="d-flex justify-content-between gap-3 flex-wrap mb-3">
    <div class="d-flex gap-2 align-items-center flex-wrap">
        @if($savedViews->isNotEmpty())
            <select class="form-select form-select-sm" style="min-width:220px" onchange="if(this.value)location.href=this.value">
                <option value="">Saved Views...</option>
                @foreach($savedViews as $view)
                    <option value="{{ route('reports.run',['report'=>$definition,'view_id'=>$view->id]) }}" @selected($selectedView?->id===$view->id)>{{ $view->name }}{{ $view->is_default?' · Default':'' }}</option>
                @endforeach
            </select>
        @endif
    </div>
    <form method="post" action="{{ route('reports.views.store',$definition) }}" class="d-flex gap-2 flex-wrap">
        @csrf
        @foreach($parameters as $key=>$value)
            @if(!in_array($key,$sensitiveParameterKeys,true))
                <input type="hidden" name="filters[{{ $key }}]" value="{{ $value }}">
            @endif
        @endforeach
        <input class="form-control form-control-sm" name="name" placeholder="Save filter as..." required style="width:190px">
        <div class="form-check d-flex align-items-center gap-1"><input class="form-check-input" type="checkbox" name="make_default" value="1" id="default-view"><label class="form-check-label small" for="default-view">Default</label></div>
        <button class="btn btn-sm btn-outline-primary">Save View</button>
    </form>
</div>
@elseif(in_array($definition->report_type,[\App\Models\Reports\ReportDefinition::TYPE_VISUAL,\App\Models\Reports\ReportDefinition::TYPE_SQL],true))
    @if(data_get($definition->definition_json,'description'))
        <div class="alert alert-light border">{{ data_get($definition->definition_json,'description') }}</div>
    @endif
    @if(!empty(data_get($definition->definition_json,'filters',[])))
        <div class="card mb-3"><div class="card-body small"><strong>Saved Visual Filters:</strong>
            @foreach(data_get($definition->definition_json,'filters',[]) as $f)
                <span class="badge text-bg-light border me-1">{{ $f['field'] }} {{ str_replace('_',' ',$f['operator']) }} {{ is_array($f['value']??null)?implode(', ',$f['value']):($f['value']??'') }}</span>
            @endforeach
        </div></div>
    @endif
@endif

@include('reports.partials.summary')
@include('reports.partials.chart')

@if(!empty($result->notes))
    <div class="alert alert-warning">
        @foreach($result->notes as $note)<div>{{ $note }}</div>@endforeach
    </div>
@endif

@include('reports.partials.table')

<div class="small text-muted mt-2">Rows shown: {{ number_format($result->rowCount(),0,',','.') }}. Business Unit is a record field; leaving the BU filter blank includes all Business Units present in the data.</div>
@endsection
