<div class="ws-tabs">
@foreach(['details'=>'Details','addresses'=>'Additional Address','defaults'=>'Defaults','summary'=>'Summary','sales'=>'Sales','gl'=>'GL Interface','remarks'=>'Remarks','audit'=>'Audit Trail'] as $key=>$label)<button type="button" class="ws-tab {{ $loop->first?'active':'' }}" data-ws-tab="{{ $key }}">{{ $label }}</button>@endforeach
</div>
<div class="ws-panel active" data-ws-panel="details"><div class="ws-panel-pad"><div class="ref-grid">
<section class="ref-section"><div class="ref-section-title">Billing Address</div><div class="ref-section-body"><div class="info-grid">@foreach(['address'=>'Address','billing_address_line_2'=>'Address Line 2','billing_city'=>'City','billing_kelurahan'=>'Kelurahan','billing_kecamatan'=>'Kecamatan','billing_kabupaten'=>'Kabupaten','billing_state'=>'State / Province','billing_country'=>'Country','billing_postal_code'=>'Zip Code'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
<section class="ref-section"><div class="ref-section-title">Shipping Address</div><div class="ref-section-body"><div class="info-grid">@foreach(['shipping_address'=>'Address','shipping_address_line_2'=>'Address Line 2','shipping_city'=>'City','shipping_kelurahan'=>'Kelurahan','shipping_kecamatan'=>'Kecamatan','shipping_kabupaten'=>'Kabupaten','shipping_state'=>'State / Province','shipping_country'=>'Country','shipping_postal_code'=>'Zip Code'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
<section class="ref-section"><div class="ref-section-title">Contact & Identity</div><div class="ref-section-body"><div class="info-grid">@foreach(['phone'=>'Phone','fax'=>'Fax','email'=>'Email','website'=>'Website','finance_tax_contact'=>'Finance / Tax Contact','npwp'=>'NPWP','nppkp'=>'NPPKP','id_card_no'=>'ID Card','virtual_account'=>'Virtual Account'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
<section class="ref-section"><div class="ref-section-title">Business Profile</div><div class="ref-section-body"><div class="info-grid">@foreach(['owner_name'=>'Owner','year_established'=>'Year Established','customer_since'=>'Customer Since','external_code'=>'External Code 1','external_code_2'=>'External Code 2','customer_type'=>'Customer Type','business_group'=>'Business Group','flags'=>'Flags'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
</div></div></div>
<div class="ws-panel" data-ws-panel="addresses">@include('master.partials.workspace-addresses')</div>
<div class="ws-panel" data-ws-panel="defaults"><div class="ws-panel-pad"><div class="ref-grid">
<section class="ref-section"><div class="ref-section-title">Financial Defaults</div><div class="ref-section-body"><div class="info-grid">@foreach(['currency_code'=>'Currency','credit_limit'=>'Credit Limit','no_credit'=>'No Credit','max_invoice_amount'=>'Max Invoice Amount','max_invoices'=>'Max Invoices','payment_term_days'=>'Payment Term (Days)','payment_additional_days'=>'Additional Days','due_date_origin'=>'Due Date Origin','default_discount_pct'=>'Default Discount %','extra_discount_pct'=>'Extra Discount %','default_tax_pct'=>'Default Tax %','tax_inclusive'=>'Tax Inclusive','surcharge_pct'=>'Surcharge %','so_down_payment_pct'=>'SO Down Payment %','cash_top_days'=>'Cash TOP Days'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
<section class="ref-section"><div class="ref-section-title">Sales Defaults</div><div class="ref-section-body"><div class="info-grid">@foreach(['sales_person_name'=>'Sales Person','so_delivery_term_days'=>'SO Delivery Term (Days)','arrival_days'=>'Arrival Days','fob'=>'FOB','shipper'=>'Shipper','collector'=>'Collector','default_price_level_id'=>'Price Level','channel'=>'Channel','area'=>'Area','sub_area'=>'Sub-area','rank'=>'Rank','scale'=>'Scale','status_code'=>'Status','discount_rules'=>'Discount Rules'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
<section class="ref-section wide"><div class="ref-section-title">Rules & Properties</div><div class="ref-section-body"><div class="switch-grid">@foreach(['always_require_so'=>'Always Require SO','allow_nonpurchase_sn_return'=>'Allow Return of Non-purchased SN','allow_partial_shipment'=>'Allow Partial Shipment','prospect'=>'Prospect','sales_order_finance_approval'=>'SO Finance Approval','spb_finance_approval'=>'SPB Finance Approval','skip_overlimit_check'=>'Skip Overlimit Check','tax_not_paid'=>'Tax Not Paid','multi_price_level'=>'Multiple Price Levels','is_manufacturer'=>'Manufacturer','is_supplier'=>'Supplier','extra_bruto'=>'Extra Bruto','approved'=>'Approved','is_active'=>'Active'] as $f=>$l)<div class="flag-chip"><span>{{ $l }}</span><span class="state {{ $record->{$f}?'on':'off' }}">{{ $yesNo($record->{$f}) }}</span></div>@endforeach</div></div></section>
</div></div></div>
<div class="ws-panel" data-ws-panel="summary"><div class="ws-composite"><aside class="ws-subnav">@foreach(['overview'=>'Summary','ledger'=>'Customer Ledger','aging'=>'Receivable Summary','pending'=>'Pending Invoices','payments'=>'Payment History'] as $k=>$l)<button type="button" class="ws-subtab {{ $loop->first?'active':'' }}" data-subtab="{{ $k }}">{{ $l }}</button>@endforeach</aside><div class="ws-subcontent">
<div class="ws-subpanel active" data-subpanel="overview"><div class="ws-kpi-row"><div class="ws-kpi"><span>Current Balance</span><strong>{{ $money($summary->current_balance) }}</strong></div><div class="ws-kpi"><span>Credit Limit</span><strong>{{ $money($summary->credit_limit) }}</strong></div><div class="ws-kpi"><span>Last Invoice</span><strong>{{ $summary->last_invoice?->document_no ?? '-' }}</strong><small>{{ $summary->last_invoice?$date($summary->last_invoice->document_date):'' }}</small></div><div class="ws-kpi"><span>Last Payment</span><strong>{{ $summary->last_payment?->document_number ?? '-' }}</strong><small>{{ $summary->last_payment?$date($summary->last_payment->posting_at):'' }}</small></div></div></div>
<div class="ws-subpanel" data-subpanel="ledger"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Date</th><th>Document #</th><th>Type</th><th>Description</th><th class="ws-num">Debit</th><th class="ws-num">Credit</th><th class="ws-num">Balance</th></tr></thead><tbody>@forelse($ledgerRows as $r)<tr><td>{{ $date($r->posting_at,'d M Y H:i') }}</td><td>{{ $r->document_number }}</td><td>{{ $r->document_type }}</td><td>{{ $r->description ?: '-' }}</td><td class="ws-num">{{ $money($r->debit) }}</td><td class="ws-num">{{ $money($r->credit) }}</td><td class="ws-num fw-bold">{{ $money($r->running_balance) }}</td></tr>@empty<tr><td colspan="7" class="ws-empty">No customer ledger.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="aging"><div class="ws-kpi-row"><div class="ws-kpi"><span>Not Due</span><strong>{{ $money($aging->not_due) }}</strong></div><div class="ws-kpi"><span>1–30 Days</span><strong>{{ $money($aging->days_1_30) }}</strong></div><div class="ws-kpi"><span>31–60 Days</span><strong>{{ $money($aging->days_31_60) }}</strong></div><div class="ws-kpi"><span>61–90 Days</span><strong>{{ $money($aging->days_61_90) }}</strong></div><div class="ws-kpi"><span>Over 90 Days</span><strong>{{ $money($aging->over_90) }}</strong></div><div class="ws-kpi"><span>Total Receivable</span><strong>{{ $money($aging->total) }}</strong></div></div><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Invoice</th><th>Posting</th><th>Due Date</th><th class="ws-num">Days Overdue</th><th class="ws-num">Outstanding</th></tr></thead><tbody>@forelse($aging->rows as $r)<tr><td>{{ $r->document_number }}</td><td>{{ $date($r->posting_at) }}</td><td>{{ $date($r->due_date) }}</td><td class="ws-num">{{ $r->overdue_days }}</td><td class="ws-num">{{ $money($r->outstanding) }}</td></tr>@empty<tr><td colspan="5" class="ws-empty">No outstanding receivable.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="pending"><div class="ws-note">Outstanding is estimated FIFO from posted Customer Ledger because invoice-level payment allocation is not yet available.</div><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Invoice</th><th>Date</th><th>Type</th><th class="ws-num">Invoice Amount</th><th class="ws-num">Payment Applied</th><th class="ws-num">Outstanding</th><th class="ws-num">Days Open</th></tr></thead><tbody>@forelse($pendingInvoices as $r)<tr><td>{{ $r->document_number }}</td><td>{{ $date($r->posting_at) }}</td><td>{{ $r->document_type }}</td><td class="ws-num">{{ $money($r->amount) }}</td><td class="ws-num">{{ $money($r->paid_estimate) }}</td><td class="ws-num fw-bold">{{ $money($r->outstanding) }}</td><td class="ws-num">{{ $r->days_open }}</td></tr>@empty<tr><td colspan="7" class="ws-empty">No pending invoices.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="payments"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Date</th><th>Document #</th><th>Type</th><th>Description</th><th class="ws-num">Payment</th></tr></thead><tbody>@forelse($paymentHistory as $r)<tr><td>{{ $date($r->posting_at,'d M Y H:i') }}</td><td>{{ $r->document_number }}</td><td>{{ $r->document_type }}</td><td>{{ $r->description ?: '-' }}</td><td class="ws-num">{{ $money($r->credit) }}</td></tr>@empty<tr><td colspan="5" class="ws-empty">No payment history.</td></tr>@endforelse</tbody></table></div></div>
</div></div></div>
<div class="ws-panel" data-ws-panel="sales"><div class="ws-composite"><aside class="ws-subnav">@foreach(['history'=>'Sales History','orders'=>'Outstanding Sales Orders','shipments'=>'Uninvoiced Shipment'] as $k=>$l)<button type="button" class="ws-subtab {{ $loop->first?'active':'' }}" data-subtab="{{ $k }}">{{ $l }}</button>@endforeach</aside><div class="ws-subcontent">
<div class="ws-subpanel active" data-subpanel="history"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Invoice Number</th><th>Date</th><th>Item Code</th><th>Item Name</th><th class="ws-num">Qty</th><th>UOM</th><th class="ws-num">Price</th><th class="ws-num">Discount</th><th class="ws-num">Disc 2 %</th><th class="ws-num">Line Total</th><th class="ws-num">Tax</th><th>Remarks</th></tr></thead><tbody>@forelse($salesHistory as $r)<tr><td>{{ $r->document_no }}</td><td>{{ $date($r->document_date) }}</td><td>{{ $r->item_code }}</td><td>{{ $r->item_name }}</td><td class="ws-num">{{ $qty($r->quantity) }}</td><td>{{ $r->uom_code ?? '-' }}</td><td class="ws-num">{{ $money($r->unit_price) }}</td><td class="ws-num">{{ $money($r->discount_amount) }}</td><td class="ws-num">{{ $qty($r->manual_discount_pct) }}</td><td class="ws-num">{{ $money($r->line_total) }}</td><td class="ws-num">{{ $money($r->tax_amount) }}</td><td>{{ $r->notes ?: '-' }}</td></tr>@empty<tr><td colspan="12" class="ws-empty">No sales history.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="orders"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>SO #</th><th>Date</th><th>Status</th><th>Currency</th><th class="ws-num">Subtotal</th><th class="ws-num">Discount</th><th class="ws-num">Tax</th><th class="ws-num">Grand Total</th><th>Notes</th></tr></thead><tbody>@forelse($outstandingSalesOrders as $r)<tr><td>{{ $r->document_no }}</td><td>{{ $date($r->document_date) }}</td><td>{{ $r->status }}</td><td>{{ $r->currency_code }}</td><td class="ws-num">{{ $money($r->subtotal) }}</td><td class="ws-num">{{ $money($r->discount_total) }}</td><td class="ws-num">{{ $money($r->tax_total) }}</td><td class="ws-num">{{ $money($r->grand_total) }}</td><td>{{ $r->notes ?: '-' }}</td></tr>@empty<tr><td colspan="9" class="ws-empty">No outstanding sales orders.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="shipments"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Shipment #</th><th>Date</th><th>Status</th><th>Currency</th><th class="ws-num">Grand Total</th><th>Notes</th></tr></thead><tbody>@forelse($uninvoicedShipments as $r)<tr><td>{{ $r->document_no }}</td><td>{{ $date($r->document_date) }}</td><td>{{ $r->status }}</td><td>{{ $r->currency_code }}</td><td class="ws-num">{{ $money($r->grand_total) }}</td><td>{{ $r->notes ?: '-' }}</td></tr>@empty<tr><td colspan="6" class="ws-empty">No uninvoiced shipments.</td></tr>@endforelse</tbody></table></div></div>
</div></div></div>
<div class="ws-panel" data-ws-panel="gl"><div class="ws-panel-pad"><div class="ref-grid"><section class="ref-section"><div class="ref-section-title">Posting Groups</div><div class="ref-section-body"><div class="info-grid">@foreach(['customer_posting_group_id'=>'Customer Posting Group','tax_posting_group_id'=>'Tax Posting Group'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section><section class="ref-section"><div class="ref-section-title">Receivable Account</div><div class="ref-section-body"><div class="info-grid"><div class="info-label">Receivable Account</div><div class="info-value">{{ $fieldValue('receivable_account_id') }}</div></div></div></section></div></div></div>
<div class="ws-panel" data-ws-panel="remarks"><div class="ws-panel-pad"><div class="spec-box">{{ $record->remarks ?: '-' }}</div></div></div>
<div class="ws-panel" data-ws-panel="audit">@include('master.partials.workspace-audit')</div>
