@php
    $uomByLevel = $record->uoms->keyBy('level');
    $flags = [
        'require_serial_numbers'=>'Require Serial Numbers','unique_serial_number'=>'Unique Serial Number','auto_uom_conversion'=>'Automatic UOM Conversion',
        'ignore_cost_verification'=>'Ignore COG Verification','consignment_goods'=>'Consignment Goods','no_tax'=>'No Tax','allow_sales_bonus'=>'Allow Sales Bonus',
        'purchase_sales_by_weight'=>'Purchase & Sales by Weight','can_be_sold'=>'Can Be Sold','can_be_purchased'=>'Can Be Purchased','can_be_used'=>'Can Be Used',
        'is_confidential'=>'Confidential','price_hold'=>'Price Hold','is_discontinued'=>'Discontinued','is_active'=>'Active',
    ];
@endphp
<div class="ws-tabs">
    @foreach(['details'=>'Details','gl'=>'GL Interface','properties'=>'Properties','balance'=>'Balance','planning'=>'Planning','prices'=>'Prices','aliases'=>'Aliases','history'=>'History & Statistics','spec'=>'Specification & Remarks','audit'=>'Audit Trail'] as $key=>$label)
        <button type="button" class="ws-tab {{ $loop->first?'active':'' }}" data-ws-tab="{{ $key }}">{{ $label }}</button>
    @endforeach
</div>

<div class="ws-panel active" data-ws-panel="details"><div class="ws-panel-pad"><div class="ref-grid">
    <section class="ref-section"><div class="ref-section-title">Classification</div><div class="ref-section-body"><div class="info-grid">
        @foreach(['brand_id'=>'Brand','category_id'=>'Category','family'=>'Family','sub_family'=>'Sub-family','manufacturer'=>'Manufacturer','price_group'=>'Price Group','incentive_schedule'=>'Incentive Schedule','costing_method'=>'Cost Method'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach
    </div></div></section>
    <section class="ref-section"><div class="ref-section-title">Quantity Levels</div><div class="ref-section-body"><div class="table-responsive"><table class="table table-sm ws-table mb-0"><thead><tr><th>Level</th><th>UOM</th><th class="ws-num">Conversion</th><th>Sales</th><th>Purchase</th></tr></thead><tbody>
        <tr><td>1st</td><td>{{ $record->baseUom?->code ?? '-' }}</td><td class="ws-num">1,000000</td><td>Yes</td><td>Yes</td></tr>
        @foreach([2=>'2nd',3=>'3rd',4=>'4th'] as $level=>$label) @php $u=$uomByLevel->get($level); @endphp
        <tr><td>{{ $label }}</td><td>{{ $u?->uom?->code ?? '-' }}</td><td class="ws-num">{{ $u?$qty($u->conversion_qty):'-' }}</td><td>{{ $u?$yesNo($u->is_sales_uom):'-' }}</td><td>{{ $u?$yesNo($u->is_purchase_uom):'-' }}</td></tr>
        @if($u && $canEdit)<tr><td colspan="5" class="pt-0"><details><summary class="btn btn-sm btn-link px-0">Edit {{ $label }} UOM</summary><form method="post" action="{{ route('master.item-uoms.update',[$record,$u]) }}" class="row g-2 align-items-end">@csrf @method('PUT')<input type="hidden" name="level" value="{{ $level }}"><div class="col-md-3"><label class="form-label small">UOM</label><select class="form-select form-select-sm" name="uom_id" required>@foreach($options['uoms']??[] as $id=>$name)<option value="{{ $id }}" @selected((string)$u->uom_id===(string)$id)>{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Conversion Qty</label><input class="form-control form-control-sm" type="number" step="0.000001" min="0.000001" name="conversion_qty" value="{{ $u->conversion_qty }}" required></div><div class="col-md-2"><input type="hidden" name="is_sales_uom" value="0"><label class="small"><input type="checkbox" name="is_sales_uom" value="1" @checked($u->is_sales_uom)> Sales UOM</label></div><div class="col-md-2"><input type="hidden" name="is_purchase_uom" value="0"><label class="small"><input type="checkbox" name="is_purchase_uom" value="1" @checked($u->is_purchase_uom)> Purchase UOM</label></div><div class="col-md-2"><button class="btn btn-sm btn-primary">Save</button></div></form><form method="post" action="{{ route('master.item-uoms.destroy',[$record,$u]) }}" class="mt-1">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete Level</button></form></details></td></tr>@endif
        @endforeach
    </tbody></table></div>@if($canEdit)<details class="mt-2"><summary class="btn btn-sm btn-outline-primary">Add UOM Level</summary><form method="post" action="{{ route('master.item-uoms.store',$record) }}" class="row g-2 align-items-end mt-1">@csrf<div class="col-md-2"><label class="form-label small">Level</label><select class="form-select form-select-sm" name="level">@foreach([2=>'2nd',3=>'3rd',4=>'4th'] as $lv=>$nm)<option value="{{ $lv }}">{{ $nm }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">UOM</label><select class="form-select form-select-sm" name="uom_id" required>@foreach($options['uoms']??[] as $id=>$name)<option value="{{ $id }}">{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Conversion Qty</label><input class="form-control form-control-sm" type="number" step="0.000001" min="0.000001" name="conversion_qty" value="1" required></div><div class="col-md-2"><input type="hidden" name="is_sales_uom" value="0"><label class="small"><input type="checkbox" name="is_sales_uom" value="1"> Sales UOM</label></div><div class="col-md-2"><input type="hidden" name="is_purchase_uom" value="0"><label class="small"><input type="checkbox" name="is_purchase_uom" value="1"> Purchase UOM</label><button class="btn btn-sm btn-primary d-block mt-2">Add</button></div></form></details>@endif</div></section>
    <section class="ref-section"><div class="ref-section-title">Dimension and Weight</div><div class="ref-section-body"><div class="info-grid">
        @foreach(['length'=>'Length (mm)','width'=>'Width (mm)','thickness'=>'Thickness (cm)','net_weight'=>'Net Weight (kg)','gross_weight'=>'Gross Weight (kg)','volume'=>'Volume (M3)'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach
    </div></div></section>
    <section class="ref-section"><div class="ref-section-title">Critical Limits</div><div class="ref-section-body"><div class="info-grid">
        @foreach(['max_quantity'=>'Maximum','min_quantity'=>'Minimum','reorder_level'=>'Reorder Level','base_uom_id'=>'Base UOM','class_code'=>'Class','item_type'=>'Type'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach
    </div></div></section>
</div></div></div>

<div class="ws-panel" data-ws-panel="gl"><div class="ws-panel-pad"><div class="ref-grid">
    <section class="ref-section"><div class="ref-section-title">Posting Groups</div><div class="ref-section-body"><div class="info-grid">@foreach(['inventory_posting_group_id'=>'Inventory Posting Group','general_product_posting_group_id'=>'General Product Posting Group','tax_posting_group_id'=>'Tax Posting Group'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
    <section class="ref-section"><div class="ref-section-title">Fallback Accounts</div><div class="ref-section-body"><div class="info-grid">@foreach(['inventory_account_id'=>'Inventory Account','sales_account_id'=>'Sales Account','cogs_account_id'=>'COGS Account','purchase_account_id'=>'Purchase Account','adjustment_account_id'=>'Adjustment Account'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
</div></div></div>

<div class="ws-panel" data-ws-panel="properties"><div class="ws-panel-pad"><div class="ref-grid">
    <section class="ref-section wide"><div class="ref-section-title">Properties</div><div class="ref-section-body"><div class="switch-grid">@foreach($flags as $f=>$l)<div class="flag-chip"><span>{{ $l }}</span><span class="state {{ $record->{$f}?'on':'off' }}">{{ $yesNo($record->{$f}) }}</span></div>@endforeach</div></div></section>
    <section class="ref-section"><div class="ref-section-title">Product Attributes</div><div class="ref-section-body"><div class="info-grid">@foreach(['size_label'=>'Size','color_label'=>'Color','size_ratio'=>'Ratio','grade'=>'Grade','reward_points'=>'Reward Points','default_warehouse_id'=>'Default Warehouse'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
    <section class="ref-section"><div class="ref-section-title">Warranty</div><div class="ref-section-body"><div class="info-grid"><div class="info-label">Warranty from Supplier</div><div class="info-value">{{ $record->warranty_supplier_months }} month(s)</div><div class="info-label">Warranty to Customer</div><div class="info-value">{{ $record->warranty_customer_months }} month(s)</div></div></div></section>
</div></div></div>

<div class="ws-panel" data-ws-panel="balance"><div class="ws-kpi-row">
    <div class="ws-kpi"><span>On Hand</span><strong>{{ $qty($stockByWarehouse->sum('balance')) }}</strong></div><div class="ws-kpi"><span>Pending</span><strong>{{ $qty($stockByWarehouse->sum('pending')) }}</strong></div><div class="ws-kpi"><span>Blocked / Allocated</span><strong>{{ $qty($stockByWarehouse->sum('blocked_allocated')) }}</strong></div><div class="ws-kpi"><span>Available</span><strong>{{ $qty($stockByWarehouse->sum('available')) }}</strong></div>
</div><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Warehouse</th><th>Name</th><th class="ws-num">Pending</th><th class="ws-num">On Hand</th><th class="ws-num">Blocked / Allocated</th><th class="ws-num">Available</th></tr></thead><tbody>@forelse($stockByWarehouse as $r)<tr><td>{{ $r->code }}</td><td>{{ $r->name }}</td><td class="ws-num">{{ $qty($r->pending) }}</td><td class="ws-num">{{ $qty($r->balance) }}</td><td class="ws-num">{{ $qty($r->blocked_allocated) }}</td><td class="ws-num fw-bold">{{ $qty($r->available) }}</td></tr>@empty<tr><td colspan="6" class="ws-empty">No warehouse balance.</td></tr>@endforelse</tbody></table></div></div>

<div class="ws-panel" data-ws-panel="planning"><div class="ws-panel-pad"><div class="ref-grid">
    <section class="ref-section"><div class="ref-section-title">Purchase Planning</div><div class="ref-section-body"><div class="info-grid">@foreach(['procurement_method'=>'Procurement Method','order_interval'=>'Order Interval','min_order'=>'Minimum Order','order_multiple'=>'Order Multiple','lead_time_days'=>'Lead Time (Days)','default_vendor_id'=>'Supplier'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
    <section class="ref-section"><div class="ref-section-title">Sales / Lifecycle Planning</div><div class="ref-section-body"><div class="info-grid">@foreach(['sales_min_order'=>'Sales Minimum Order','lifetime_months'=>'Lifetime (Months)','min_markup_pct'=>'Minimum Markup %','max_markup_pct'=>'Maximum Markup %','reorder_level'=>'Reorder Level','default_warehouse_id'=>'Default Warehouse'] as $f=>$l)<div class="info-label">{{ $l }}</div><div class="info-value">{{ $fieldValue($f) }}</div>@endforeach</div></div></section>
</div></div></div>

<div class="ws-panel" data-ws-panel="prices"><div class="ws-note">Price history follows approved Item Price records and effective dates.</div><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Price Level</th><th>UOM</th><th>Currency</th><th class="ws-num">Price</th><th>Valid From</th><th>Valid To</th><th>Active</th></tr></thead><tbody>@forelse($priceHistory as $p)<tr><td>{{ $p->priceLevel?->code }} - {{ $p->priceLevel?->name }}</td><td>{{ $p->uom?->code ?? '-' }}</td><td>{{ $p->currency_code }}</td><td class="ws-num">{{ $money($p->price) }}</td><td>{{ $date($p->effective_from) }}</td><td>{{ $date($p->effective_to) }}</td><td>{{ $yesNo($p->is_active) }}</td></tr>@empty<tr><td colspan="7" class="ws-empty">No price history.</td></tr>@endforelse</tbody></table></div></div>

<div class="ws-panel" data-ws-panel="aliases"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Alias / Barcode</th><th>Type</th><th>UOM</th><th>Description</th><th>Active</th>@if($canEdit)<th>Action</th>@endif</tr></thead><tbody>@forelse($record->aliases as $a)<tr><td class="fw-bold">{{ $a->alias_code }}</td><td>{{ $a->alias_type }}</td><td>{{ $a->uom?->code ?? '-' }}</td><td>{{ $a->description ?: '-' }}</td><td>{{ $yesNo($a->is_active) }}</td>@if($canEdit)<td><details><summary class="btn btn-sm btn-outline-primary">Edit</summary><form class="mt-2" method="post" action="{{ route('master.item-aliases.update',[$record,$a]) }}">@csrf @method('PUT')<div class="row g-2"><div class="col-md-3"><input class="form-control form-control-sm" name="alias_code" value="{{ $a->alias_code }}" required></div><div class="col-md-2"><select class="form-select form-select-sm" name="alias_type">@foreach(['BARCODE','SUPPLIER','CUSTOMER','INTERNAL','OTHER'] as $t)<option @selected($a->alias_type===$t)>{{ $t }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select form-select-sm" name="uom_id"><option value="">-</option>@foreach($options['uoms']??[] as $id=>$name)<option value="{{ $id }}" @selected((string)$a->uom_id===(string)$id)>{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><input class="form-control form-control-sm" name="description" value="{{ $a->description }}"></div><div class="col-md-2"><input type="hidden" name="is_active" value="0"><label class="small"><input type="checkbox" name="is_active" value="1" @checked($a->is_active)> Active</label><button class="btn btn-sm btn-primary ms-2">Save</button></div></div></form><form class="mt-1" method="post" action="{{ route('master.item-aliases.destroy',[$record,$a]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete Alias</button></form></details></td>@endif</tr>@empty<tr><td colspan="{{ $canEdit?6:5 }}" class="ws-empty">No aliases or barcodes.</td></tr>@endforelse</tbody></table></div>
@if($canEdit)<form class="ws-form-mini" method="post" action="{{ route('master.item-aliases.store',$record) }}">@csrf<div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small">Alias / Barcode</label><input class="form-control form-control-sm" name="alias_code" required></div><div class="col-md-2"><label class="form-label small">Type</label><select class="form-select form-select-sm" name="alias_type">@foreach(['BARCODE','SUPPLIER','CUSTOMER','INTERNAL','OTHER'] as $t)<option>{{ $t }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label small">UOM</label><select class="form-select form-select-sm" name="uom_id"><option value="">-</option>@foreach($options['uoms']??[] as $id=>$name)<option value="{{ $id }}">{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Description</label><input class="form-control form-control-sm" name="description"></div><div class="col-md-2"><input type="hidden" name="is_active" value="0"><label class="small d-block mb-2"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="btn btn-sm btn-primary">Add Alias</button></div></div></form>@endif</div>

<div class="ws-panel" data-ws-panel="history"><div class="ws-composite"><aside class="ws-subnav">@foreach(['activity'=>'Activities History','stock'=>'Stock Value Calculation','annual'=>'Annual Summary','sales-orders'=>'Outstanding Sales Orders','purchase-orders'=>'Outstanding Purchase Orders'] as $key=>$label)<button type="button" class="ws-subtab {{ $loop->first?'active':'' }}" data-subtab="{{ $key }}">{{ $label }}</button>@endforeach</aside><div class="ws-subcontent">
<div class="ws-subpanel active" data-subpanel="activity"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Date</th><th>Document #</th><th>Type</th><th>Warehouse / Location</th><th class="ws-num">In</th><th class="ws-num">Out</th><th class="ws-num">Unit Cost</th><th>Description</th></tr></thead><tbody>@forelse($ledgerRows as $r)<tr><td>{{ $date($r->posting_at,'d M Y H:i') }}</td><td>{{ $r->document_number }}</td><td>{{ $r->document_type }}</td><td>{{ $r->warehouse?->code ?? '-' }} / {{ $r->location?->code ?? '-' }}</td><td class="ws-num">{{ $qty($r->qty_in) }}</td><td class="ws-num">{{ $qty($r->qty_out) }}</td><td class="ws-num">{{ $money($r->unit_cost) }}</td><td>{{ $r->description ?: '-' }}</td></tr>@empty<tr><td colspan="8" class="ws-empty">No item ledger history.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="stock"><div class="ws-note">COGS is read from posted quantity × unit cost; this view does not recalculate the costing engine.</div><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Document #</th><th>Document Type</th><th>Date</th><th>UOM</th><th class="ws-num">In</th><th class="ws-num">Out</th><th class="ws-num">Cost / Price</th><th class="ws-num">Item COG</th><th class="ws-num">Running Qty</th><th class="ws-num">Running Value</th><th class="ws-num">Current COG</th><th>Currency</th></tr></thead><tbody>@forelse($valuationRows as $r)<tr><td>{{ $r->document_number }}</td><td>{{ $r->document_type }}</td><td>{{ $date($r->posting_at,'d M Y H:i') }}</td><td>{{ $record->baseUom?->code ?? '-' }}</td><td class="ws-num">{{ $qty($r->qty_in) }}</td><td class="ws-num">{{ $qty($r->qty_out) }}</td><td class="ws-num">{{ $money($r->unit_cost) }}</td><td class="ws-num">{{ $money($r->cogs) }}</td><td class="ws-num">{{ $qty($r->running_qty) }}</td><td class="ws-num">{{ $money($r->running_value) }}</td><td class="ws-num">{{ $money($r->average_cost) }}</td><td>IDR</td></tr>@empty<tr><td colspan="12" class="ws-empty">No stock value history.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="annual"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Period</th><th class="ws-num">Qty In</th><th class="ws-num">Qty Out</th><th class="ws-num">Value In</th><th class="ws-num">COGS</th></tr></thead><tbody>@forelse($annualItemSummary as $r)<tr><td>{{ $r->month_name }} {{ $r->year }}</td><td class="ws-num">{{ $qty($r->qty_in) }}</td><td class="ws-num">{{ $qty($r->qty_out) }}</td><td class="ws-num">{{ $money($r->value_in) }}</td><td class="ws-num">{{ $money($r->cogs) }}</td></tr>@empty<tr><td colspan="5" class="ws-empty">No activity in current year.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="sales-orders"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>Order #</th><th>Date</th><th>Status</th><th>Customer</th><th class="ws-num">Qty</th><th class="ws-num">Unit Price</th><th class="ws-num">Line Total</th></tr></thead><tbody>@forelse($outstandingSalesOrders as $r)<tr><td>{{ $r->document_no }}</td><td>{{ $date($r->document_date) }}</td><td>{{ $r->status }}</td><td>{{ $r->partner_code }} - {{ $r->partner_name }}</td><td class="ws-num">{{ $qty($r->quantity) }}</td><td class="ws-num">{{ $money($r->unit_price) }}</td><td class="ws-num">{{ $money($r->line_total) }}</td></tr>@empty<tr><td colspan="7" class="ws-empty">No outstanding sales orders.</td></tr>@endforelse</tbody></table></div></div>
<div class="ws-subpanel" data-subpanel="purchase-orders"><div class="ws-table-wrap"><table class="table table-hover ws-table mb-0"><thead><tr><th>PO #</th><th>Date</th><th>Status</th><th>Supplier</th><th class="ws-num">Qty</th><th class="ws-num">Unit Price</th><th class="ws-num">Line Total</th></tr></thead><tbody>@forelse($outstandingPurchaseOrders as $r)<tr><td>{{ $r->document_no }}</td><td>{{ $date($r->document_date) }}</td><td>{{ $r->status }}</td><td>{{ $r->partner_code }} - {{ $r->partner_name }}</td><td class="ws-num">{{ $qty($r->quantity) }}</td><td class="ws-num">{{ $money($r->unit_price) }}</td><td class="ws-num">{{ $money($r->line_total) }}</td></tr>@empty<tr><td colspan="7" class="ws-empty">No outstanding purchase orders.</td></tr>@endforelse</tbody></table></div></div>
</div></div></div>

<div class="ws-panel" data-ws-panel="spec"><div class="ws-panel-pad"><div class="ref-grid"><section class="ref-section"><div class="ref-section-title">Specification</div><div class="ref-section-body"><div class="spec-box">{{ $record->specification ?: '-' }}</div></div></section><section class="ref-section"><div class="ref-section-title">Remarks</div><div class="ref-section-body"><div class="spec-box">{{ $record->remarks ?: '-' }}</div></div></section></div></div></div>

<div class="ws-panel" data-ws-panel="audit">@include('master.partials.workspace-audit')</div>
