<div class="ws-panel-pad">
    <div class="address-grid">
        @forelse($record->addresses as $a)
            <div class="address-card">
                <div class="d-flex justify-content-between gap-2"><div><div class="address-type">{{ $a->address_type }} @if($a->is_default)• Default @endif</div><div class="address-title">{{ $a->label ?: ($a->contact_person ?: 'Address') }}</div></div><span class="ws-pill {{ $a->is_active?'live':'off' }}">{{ $a->is_active?'Active':'Inactive' }}</span></div>
                <div class="address-text">{{ $a->address }}
{{ collect([$a->city,$a->state,$a->postal_code,$a->country])->filter()->implode(', ') }}
@if($a->phone){{ $a->phone }}@endif</div>
                @if($canEdit)<details class="mt-2"><summary class="btn btn-sm btn-outline-primary">Edit Address</summary><form class="mt-2" method="post" action="{{ route('master.partner-addresses.update',[$workspaceType,$record->id,$a]) }}">@csrf @method('PUT')
                    <div class="row g-2"><div class="col-md-3"><select class="form-select form-select-sm" name="address_type">@foreach(['BILLING','SHIPPING','OFFICE','WAREHOUSE','TAX','OTHER'] as $t)<option @selected($a->address_type===$t)>{{ $t }}</option>@endforeach</select></div><div class="col-md-4"><input class="form-control form-control-sm" name="label" value="{{ $a->label }}" placeholder="Label"></div><div class="col-md-5"><input class="form-control form-control-sm" name="contact_person" value="{{ $a->contact_person }}" placeholder="Contact person"></div><div class="col-12"><textarea class="form-control form-control-sm" name="address" required>{{ $a->address }}</textarea></div><div class="col-md-3"><input class="form-control form-control-sm" name="city" value="{{ $a->city }}" placeholder="City"></div><div class="col-md-3"><input class="form-control form-control-sm" name="state" value="{{ $a->state }}" placeholder="State"></div><div class="col-md-2"><input class="form-control form-control-sm" name="postal_code" value="{{ $a->postal_code }}" placeholder="Postal code"></div><div class="col-md-2"><input class="form-control form-control-sm" name="country" value="{{ $a->country }}" placeholder="Country"></div><div class="col-md-2"><input class="form-control form-control-sm" name="phone" value="{{ $a->phone }}" placeholder="Phone"></div><div class="col-12 d-flex gap-3 align-items-center"><input type="hidden" name="is_default" value="0"><label class="small"><input type="checkbox" name="is_default" value="1" @checked($a->is_default)> Default for type</label><input type="hidden" name="is_active" value="0"><label class="small"><input type="checkbox" name="is_active" value="1" @checked($a->is_active)> Active</label><button class="btn btn-sm btn-primary">Save</button></div></div>
                </form><form class="mt-1" method="post" action="{{ route('master.partner-addresses.destroy',[$workspaceType,$record->id,$a]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete Address</button></form></details>@endif
            </div>
        @empty<div class="muted-box" style="grid-column:1/-1">No additional addresses.</div>@endforelse
    </div>
</div>
@if($canEdit)<form class="ws-form-mini" method="post" action="{{ route('master.partner-addresses.store',[$workspaceType,$record->id]) }}">@csrf<div class="row g-2 align-items-end"><div class="col-md-2"><label class="form-label small">Type</label><select class="form-select form-select-sm" name="address_type">@foreach(['BILLING','SHIPPING','OFFICE','WAREHOUSE','TAX','OTHER'] as $t)<option>{{ $t }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Label</label><input class="form-control form-control-sm" name="label"></div><div class="col-md-3"><label class="form-label small">Contact Person</label><input class="form-control form-control-sm" name="contact_person"></div><div class="col-md-4"><label class="form-label small">Phone</label><input class="form-control form-control-sm" name="phone"></div><div class="col-12"><label class="form-label small">Address</label><textarea class="form-control form-control-sm" name="address" required></textarea></div><div class="col-md-3"><label class="form-label small">City</label><input class="form-control form-control-sm" name="city"></div><div class="col-md-3"><label class="form-label small">State</label><input class="form-control form-control-sm" name="state"></div><div class="col-md-2"><label class="form-label small">Postal Code</label><input class="form-control form-control-sm" name="postal_code"></div><div class="col-md-2"><label class="form-label small">Country</label><input class="form-control form-control-sm" name="country"></div><div class="col-md-2"><input type="hidden" name="is_default" value="0"><label class="small d-block mb-1"><input type="checkbox" name="is_default" value="1"> Default</label><input type="hidden" name="is_active" value="0"><label class="small d-block mb-2"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="btn btn-sm btn-primary">Add Address</button></div></div></form>@endif
