<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    private function postedHeader(Blueprint $t): void { $t->id();$t->string('document_no',120)->unique();$t->date('document_date');$t->string('source_document_no',120);$t->string('currency_code',10)->default('IDR');$t->decimal('subtotal',19,4)->default(0);$t->decimal('discount_total',19,4)->default(0);$t->decimal('tax_total',19,4)->default(0);$t->decimal('grand_total',19,4)->default(0);$t->text('notes')->nullable();$t->foreignId('posted_by')->constrained('users');$t->timestamp('posted_at');$t->foreignId('gl_batch_id')->nullable()->constrained('gl_batches');$t->timestamps(); }
    private function postedLine(Blueprint $t): void { $t->id();$t->foreignId('item_id')->constrained('items');$t->string('item_code',100);$t->string('description')->nullable();$t->decimal('quantity',19,4);$t->decimal('unit_price',19,4)->default(0);$t->decimal('unit_cost',19,4)->default(0);$t->decimal('discount_amount',19,4)->default(0);$t->decimal('tax_rate',9,4)->default(0);$t->decimal('tax_amount',19,4)->default(0);$t->decimal('line_total',19,4)->default(0);$t->timestamps(); }
    public function up(): void {
        Schema::create('posted_shipments', function(Blueprint $t){$this->postedHeader($t);$t->foreignId('source_shipment_id')->unique()->constrained('shipments');$t->foreignId('customer_id')->constrained('customers');$t->foreignId('warehouse_id')->constrained('warehouses');});
        Schema::create('posted_shipment_lines', function(Blueprint $t){$this->postedLine($t);$t->foreignId('posted_shipment_id')->constrained()->cascadeOnDelete();$t->foreignId('source_shipment_line_id')->constrained('shipment_lines');$t->foreignId('source_sales_order_line_id')->constrained('sales_order_lines');});
        Schema::create('posted_sales_invoices', function(Blueprint $t){$this->postedHeader($t);$t->foreignId('source_sales_invoice_id')->unique()->constrained('sales_invoices');$t->foreignId('customer_id')->constrained('customers');$t->foreignId('customer_ledger_id')->nullable()->constrained('customer_ledgers');});
        Schema::create('posted_sales_invoice_lines', function(Blueprint $t){$this->postedLine($t);$t->foreignId('posted_sales_invoice_id')->constrained()->cascadeOnDelete();$t->foreignId('source_sales_invoice_line_id')->constrained('sales_invoice_lines');$t->foreignId('source_posted_shipment_line_id')->nullable()->constrained('posted_shipment_lines');$t->foreignId('source_sales_order_line_id')->nullable()->constrained('sales_order_lines');$t->boolean('direct_service')->default(false);});
        Schema::create('posted_receipts', function(Blueprint $t){$this->postedHeader($t);$t->foreignId('source_receipt_id')->unique()->constrained('receipts');$t->foreignId('vendor_id')->constrained('vendors');$t->foreignId('warehouse_id')->constrained('warehouses');});
        Schema::create('posted_receipt_lines', function(Blueprint $t){$this->postedLine($t);$t->foreignId('posted_receipt_id')->constrained()->cascadeOnDelete();$t->foreignId('source_receipt_line_id')->constrained('receipt_lines');$t->foreignId('source_purchase_order_line_id')->constrained('purchase_order_lines');});
        Schema::create('posted_purchase_invoices', function(Blueprint $t){$this->postedHeader($t);$t->foreignId('source_purchase_invoice_id')->unique()->constrained('purchase_invoices');$t->foreignId('vendor_id')->constrained('vendors');$t->foreignId('vendor_ledger_id')->nullable()->constrained('vendor_ledgers');});
        Schema::create('posted_purchase_invoice_lines', function(Blueprint $t){$this->postedLine($t);$t->foreignId('posted_purchase_invoice_id')->constrained()->cascadeOnDelete();$t->foreignId('source_purchase_invoice_line_id')->constrained('purchase_invoice_lines');$t->foreignId('source_posted_receipt_line_id')->nullable()->constrained('posted_receipt_lines');$t->foreignId('source_purchase_order_line_id')->nullable()->constrained('purchase_order_lines');$t->boolean('direct_service')->default(false);});
        Schema::create('posted_document_undos', function(Blueprint $t){$t->id();$t->string('posted_type',60);$t->unsignedBigInteger('posted_id');$t->string('reversal_document_no',120)->unique();$t->foreignId('reversal_gl_batch_id')->nullable()->constrained('gl_batches');$t->foreignId('undone_by')->constrained('users');$t->timestamp('undone_at');$t->text('reason');$t->timestamps();$t->unique(['posted_type','posted_id']);});
        Schema::table('sales_invoice_lines', function(Blueprint $t){$t->foreign('source_posted_shipment_line_id')->references('id')->on('posted_shipment_lines');});
        Schema::table('purchase_invoice_lines', function(Blueprint $t){$t->foreign('source_posted_receipt_line_id')->references('id')->on('posted_receipt_lines');});
    }
    public function down(): void { Schema::table('sales_invoice_lines',fn(Blueprint $t)=>$t->dropForeign(['source_posted_shipment_line_id'])); Schema::table('purchase_invoice_lines',fn(Blueprint $t)=>$t->dropForeign(['source_posted_receipt_line_id'])); foreach(['posted_document_undos','posted_purchase_invoice_lines','posted_purchase_invoices','posted_receipt_lines','posted_receipts','posted_sales_invoice_lines','posted_sales_invoices','posted_shipment_lines','posted_shipments'] as $table) Schema::dropIfExists($table); }
};
