<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('item_ledgers', function(Blueprint $t){$t->id();$t->dateTime('posting_at');$t->string('source_module',80);$t->string('document_type',50);$t->string('document_number',120);$t->foreignId('item_id')->constrained();$t->foreignId('warehouse_id')->constrained();$t->decimal('qty_in',19,4)->default(0);$t->decimal('qty_out',19,4)->default(0);$t->decimal('unit_cost',19,4)->default(0);$t->decimal('amount',19,4)->default(0);$t->text('description')->nullable();$t->foreignId('posted_by')->constrained('users');$t->foreignId('reversal_of_id')->nullable()->constrained('item_ledgers');$t->string('status',20)->default('POSTED');$t->timestamps();$t->index(['item_id','warehouse_id','posting_at']);$t->index('document_number');});
 Schema::create('customer_ledgers', function(Blueprint $t){$t->id();$t->dateTime('posting_at');$t->string('source_module',80);$t->string('document_type',50);$t->string('document_number',120);$t->foreignId('customer_id')->constrained();$t->decimal('debit',19,4)->default(0);$t->decimal('credit',19,4)->default(0);$t->text('description')->nullable();$t->foreignId('posted_by')->constrained('users');$t->foreignId('reversal_of_id')->nullable()->constrained('customer_ledgers');$t->string('status',20)->default('POSTED');$t->timestamps();$t->index(['customer_id','posting_at']);$t->index('document_number');});
 Schema::create('vendor_ledgers', function(Blueprint $t){$t->id();$t->dateTime('posting_at');$t->string('source_module',80);$t->string('document_type',50);$t->string('document_number',120);$t->foreignId('vendor_id')->constrained();$t->decimal('debit',19,4)->default(0);$t->decimal('credit',19,4)->default(0);$t->text('description')->nullable();$t->foreignId('posted_by')->constrained('users');$t->foreignId('reversal_of_id')->nullable()->constrained('vendor_ledgers');$t->string('status',20)->default('POSTED');$t->timestamps();$t->index(['vendor_id','posting_at']);$t->index('document_number');});
 Schema::create('gl_batches', function(Blueprint $t){$t->id();$t->string('document_number',120)->unique();$t->dateTime('posting_at');$t->string('source_module',80);$t->string('document_type',50);$t->text('description')->nullable();$t->foreignId('posted_by')->constrained('users');$t->foreignId('reversal_of_id')->nullable()->constrained('gl_batches');$t->string('status',20)->default('POSTED');$t->timestamps();});
 Schema::create('gl_entries', function(Blueprint $t){$t->id();$t->foreignId('gl_batch_id')->constrained('gl_batches');$t->foreignId('account_id')->constrained('chart_of_accounts');$t->decimal('debit',19,4)->default(0);$t->decimal('credit',19,4)->default(0);$t->text('description')->nullable();$t->foreignId('reversal_of_id')->nullable()->constrained('gl_entries');$t->string('status',20)->default('POSTED');$t->timestamps();$t->index(['account_id','gl_batch_id']);});
 } public function down(): void {foreach(['gl_entries','gl_batches','vendor_ledgers','customer_ledgers','item_ledgers'] as $table) Schema::dropIfExists($table);} };
