<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('item_categories', function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_category_id')->nullable()->index();$t->string('code',50)->unique();$t->string('name');$t->boolean('is_active')->default(true);$t->timestamps();});
        Schema::create('brands', function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_brand_id')->nullable()->index();$t->string('code',50)->unique();$t->string('name');$t->boolean('is_active')->default(true);$t->timestamps();});
        Schema::table('items', function(Blueprint $t){
            $t->unsignedBigInteger('legacy_item_id')->nullable()->index(); $t->foreignId('category_id')->nullable()->constrained('item_categories'); $t->foreignId('brand_id')->nullable()->constrained('brands');
            $t->string('costing_method',40)->nullable(); $t->string('procurement_method',40)->nullable(); $t->decimal('min_quantity',19,4)->default(0); $t->decimal('max_quantity',19,4)->default(0); $t->decimal('reorder_level',19,4)->default(0); $t->decimal('min_order',19,4)->default(0); $t->unsignedInteger('lead_time_days')->default(0);
            $t->boolean('can_be_sold')->default(true); $t->boolean('can_be_purchased')->default(true); $t->boolean('is_discontinued')->default(false); $t->boolean('price_hold')->default(false); $t->text('specification')->nullable(); $t->text('remarks')->nullable();
            $t->foreignId('purchase_account_id')->nullable()->constrained('chart_of_accounts'); $t->foreignId('adjustment_account_id')->nullable()->constrained('chart_of_accounts'); $t->foreignId('default_vendor_id')->nullable()->constrained('vendors');
        });
        Schema::create('item_uoms', function(Blueprint $t){$t->id();$t->foreignId('item_id')->constrained('items')->cascadeOnDelete();$t->foreignId('uom_id')->constrained('uoms');$t->unsignedSmallInteger('level')->default(1);$t->decimal('conversion_qty',19,6)->default(1);$t->boolean('is_sales_uom')->default(false);$t->boolean('is_purchase_uom')->default(false);$t->timestamps();$t->unique(['item_id','level']);});
        Schema::table('customers', function(Blueprint $t){
            $t->unsignedBigInteger('legacy_customer_id')->nullable()->index(); $t->string('billing_city')->nullable(); $t->string('billing_state')->nullable(); $t->string('billing_country')->nullable(); $t->text('shipping_address')->nullable(); $t->string('shipping_city')->nullable(); $t->string('shipping_state')->nullable(); $t->string('shipping_country')->nullable();
            $t->string('npwp',80)->nullable(); $t->unsignedInteger('payment_term_days')->default(0); $t->foreignId('default_price_level_id')->nullable()->constrained('price_levels'); $t->boolean('multi_price_level')->default(false); $t->boolean('approved')->default(true); $t->foreignId('approved_by')->nullable()->constrained('users'); $t->timestamp('approved_at')->nullable(); $t->text('disabled_reason')->nullable();
        });
        Schema::table('vendors', function(Blueprint $t){
            $t->unsignedBigInteger('legacy_supplier_id')->nullable()->index(); $t->string('city')->nullable(); $t->string('state')->nullable(); $t->string('country')->nullable(); $t->string('npwp',80)->nullable(); $t->unsignedInteger('payment_term_days')->default(0); $t->decimal('credit_limit',19,4)->default(0); $t->string('bank_name')->nullable(); $t->string('bank_account_no')->nullable(); $t->string('account_owner')->nullable(); $t->boolean('approved')->default(true); $t->foreignId('approved_by')->nullable()->constrained('users'); $t->timestamp('approved_at')->nullable(); $t->text('disabled_reason')->nullable();
        });
        Schema::table('chart_of_accounts', function(Blueprint $t){ $t->unsignedBigInteger('legacy_account_id')->nullable()->index(); $t->string('account_category',50)->nullable(); $t->string('currency_code',10)->default('IDR'); $t->boolean('require_cost_center')->default(false); $t->string('legacy_account_type',50)->nullable(); });
        Schema::table('price_levels', function(Blueprint $t){$t->unsignedSmallInteger('sort_order')->default(100);$t->string('currency_code',10)->default('IDR');});
        Schema::table('posting_setups', function(Blueprint $t){$t->foreignId('inventory_in_transit_account_id')->nullable()->constrained('chart_of_accounts');});

        Schema::create('price_update_batches', function(Blueprint $t){$t->id();$t->string('batch_no',120)->unique();$t->string('description')->nullable();$t->string('status',20)->default('OPEN');$t->foreignId('uploaded_by')->constrained('users');$t->foreignId('released_by')->nullable()->constrained('users');$t->timestamp('released_at')->nullable();$t->foreignId('approved_by')->nullable()->constrained('users');$t->timestamp('approved_at')->nullable();$t->foreignId('rejected_by')->nullable()->constrained('users');$t->timestamp('rejected_at')->nullable();$t->text('rejection_reason')->nullable();$t->string('source_filename')->nullable();$t->timestamps();});
        Schema::create('price_update_lines', function(Blueprint $t){$t->id();$t->foreignId('price_update_batch_id')->constrained()->cascadeOnDelete();$t->foreignId('item_id')->constrained('items');$t->foreignId('price_level_id')->constrained('price_levels');$t->foreignId('uom_id')->constrained('uoms');$t->decimal('old_price',19,4)->nullable();$t->decimal('new_price',19,4);$t->date('effective_date');$t->string('validation_status',20)->default('VALID');$t->text('validation_message')->nullable();$t->text('notes')->nullable();$t->timestamps();$t->unique(['price_update_batch_id','item_id','price_level_id','uom_id']);});
        Schema::create('item_prices', function(Blueprint $t){$t->id();$t->foreignId('item_id')->constrained('items');$t->foreignId('price_level_id')->constrained('price_levels');$t->foreignId('uom_id')->constrained('uoms');$t->string('currency_code',10)->default('IDR');$t->decimal('price',19,4);$t->date('effective_from');$t->date('effective_to')->nullable();$t->foreignId('price_update_batch_id')->nullable()->constrained('price_update_batches');$t->foreignId('approved_by')->nullable()->constrained('users');$t->timestamp('approved_at')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['item_id','price_level_id','uom_id','effective_from']);});
        Schema::create('customer_price_level_assignments', function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained('customers')->cascadeOnDelete();$t->foreignId('price_level_id')->constrained('price_levels');$t->boolean('is_default')->default(false);$t->timestamps();$t->unique(['customer_id','price_level_id']);});

        foreach(['sales_requests','sales_orders','sales_invoices'] as $table){Schema::table($table,function(Blueprint $t){$t->foreignId('price_level_id')->nullable()->constrained('price_levels');});}
        foreach(['sales_request_lines','sales_order_lines','sales_invoice_lines'] as $table){Schema::table($table,function(Blueprint $t){$t->foreignId('price_level_id')->nullable()->constrained('price_levels');$t->decimal('list_unit_price',19,4)->default(0);$t->decimal('location_discount_pct',9,4)->default(0);$t->decimal('bin_discount_pct',9,4)->default(0);$t->decimal('manual_discount_pct',9,4)->default(0);$t->string('discount_formula',100)->nullable();$t->decimal('net_unit_price',19,4)->default(0);});}
        Schema::table('posted_sales_invoice_lines',function(Blueprint $t){$t->foreignId('price_level_id')->nullable()->constrained('price_levels');$t->decimal('list_unit_price',19,4)->default(0);$t->decimal('location_discount_pct',9,4)->default(0);$t->decimal('bin_discount_pct',9,4)->default(0);$t->decimal('manual_discount_pct',9,4)->default(0);$t->string('discount_formula',100)->nullable();$t->decimal('net_unit_price',19,4)->default(0);});
    }
    public function down(): void {
        foreach(['sales_request_lines','sales_order_lines','sales_invoice_lines'] as $table){Schema::table($table,function(Blueprint $t) use($table){foreach(['price_level_id','list_unit_price','location_discount_pct','bin_discount_pct','manual_discount_pct','discount_formula','net_unit_price'] as $c) if(Schema::hasColumn($table,$c))$t->dropColumn($c);});}
        Schema::dropIfExists('customer_price_level_assignments');Schema::dropIfExists('item_prices');Schema::dropIfExists('price_update_lines');Schema::dropIfExists('price_update_batches');Schema::dropIfExists('item_uoms');
        Schema::table('price_levels',function(Blueprint $t){$t->dropColumn(['sort_order','currency_code']);});
        Schema::dropIfExists('brands');Schema::dropIfExists('item_categories');
    }
};
