<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('uoms', function(Blueprint $t){$t->id();$t->string('code',50)->unique();$t->string('name');$t->string('symbol',20)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('chart_of_accounts', function(Blueprint $t){$t->id();$t->foreignId('parent_id')->nullable()->constrained('chart_of_accounts');$t->string('code',100)->unique();$t->string('name');$t->string('account_type',50);$t->string('normal_balance',10)->default('DEBIT');$t->boolean('allow_posting')->default(true);$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('warehouses', function(Blueprint $t){$t->id();$t->string('code',50)->unique();$t->string('name');$t->text('address')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('price_levels', function(Blueprint $t){$t->id();$t->string('code',50)->unique();$t->string('name');$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('items', function(Blueprint $t){$t->id();$t->string('code',100)->unique();$t->string('name');$t->string('item_type',50)->default('INVENTORY');$t->foreignId('base_uom_id')->constrained('uoms');$t->foreignId('inventory_account_id')->nullable()->constrained('chart_of_accounts');$t->foreignId('sales_account_id')->nullable()->constrained('chart_of_accounts');$t->foreignId('cogs_account_id')->nullable()->constrained('chart_of_accounts');$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('customers', function(Blueprint $t){$t->id();$t->string('code',100)->unique();$t->string('name');$t->text('address')->nullable();$t->string('phone',50)->nullable();$t->string('email')->nullable();$t->foreignId('receivable_account_id')->nullable()->constrained('chart_of_accounts');$t->decimal('credit_limit',19,4)->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('vendors', function(Blueprint $t){$t->id();$t->string('code',100)->unique();$t->string('name');$t->text('address')->nullable();$t->string('phone',50)->nullable();$t->string('email')->nullable();$t->foreignId('payable_account_id')->nullable()->constrained('chart_of_accounts');$t->boolean('is_active')->default(true);$t->timestamps();});
 } public function down(): void { foreach(['vendors','customers','items','price_levels','warehouses','chart_of_accounts','uoms'] as $table) Schema::dropIfExists($table); } };
