<?php

use App\Reports\Standard\{
    AccountMovementReport,
    ApGlReconciliationReport,
    ArGlReconciliationReport,
    BalanceSheetReport,
    CashFlowReport,
    CogsDetailReport,
    CustomerAgingReport,
    CustomerOutstandingReport,
    CustomerStatementReport,
    DeadStockReport,
    ExecutiveSalesDashboardReport,
    ExecutivePurchaseDashboardReport,
    FastMovingReport,
    GeneralLedgerDetailReport,
    InventoryAgingReport,
    InventoryGlReconciliationReport,
    InventoryHealthReport,
    JournalRegisterReport,
    MonthlyPerformanceReport,
    NegativeStockReport,
    ProfitLossByBusinessUnitReport,
    ProfitLossReport,
    BusinessUnitPerformanceReport,
    PurchaseByItemReport,
    PurchaseByLocationBusinessUnitReport,
    PurchaseBySupplierReport,
    PurchaseDetailReport,
    PurchaseHistoryReport,
    PurchaseOutstandingOrdersReport,
    PurchaseOutstandingReceiptsReport,
    PurchaseSummaryReport,
    ReorderReport,
    SalesByCustomerReport,
    SalesByItemReport,
    SalesByLocationBusinessUnitReport,
    SalesBySalespersonReport,
    SalesDetailReport,
    SalesHistoryReport,
    SalesOutstandingOrdersReport,
    SalesOutstandingShipmentsReport,
    SalesSummaryReport,
    SlowMovingReport,
    StockAvailabilityReport,
    StockCardReport,
    StockMovementReport,
    StockValuationReport,
    TransferHistoryReport,
    TrialBalanceReport,
    VendorAgingReport,
    VendorOutstandingReport,
    VendorStatementReport,
    WorkingCapitalReport
};

use App\Services\Reports\Datasources\Adapters\{
    AuditActivityAdapter,
    ChartOfAccountsAdapter,
    CustomerLedgerAdapter,
    CustomerMasterAdapter,
    GeneralLedgerAdapter,
    InventoryMovementAdapter,
    ItemMasterAdapter,
    PurchaseInvoiceDetailAdapter,
    PurchaseOrderDetailAdapter,
    SalesInvoiceDetailAdapter,
    SalesOrderDetailAdapter,
    StockPositionAdapter,
    SupplierMasterAdapter,
    VendorLedgerAdapter
};

return [
    'standard' => [
        'SALES_HISTORY' => SalesHistoryReport::class,
        'SALES_SUMMARY' => SalesSummaryReport::class,
        'SALES_DETAIL' => SalesDetailReport::class,
        'SALES_BY_CUSTOMER' => SalesByCustomerReport::class,
        'SALES_BY_ITEM' => SalesByItemReport::class,
        'SALES_BY_SALESPERSON' => SalesBySalespersonReport::class,
        'SALES_BY_LOCATION_BU' => SalesByLocationBusinessUnitReport::class,
        'SALES_OUTSTANDING_ORDERS' => SalesOutstandingOrdersReport::class,
        'SALES_OUTSTANDING_SHIPMENTS' => SalesOutstandingShipmentsReport::class,
        'CUSTOMER_OUTSTANDING' => CustomerOutstandingReport::class,
        'CUSTOMER_STATEMENT' => CustomerStatementReport::class,
        'CUSTOMER_AGING' => CustomerAgingReport::class,

        'PURCHASE_HISTORY' => PurchaseHistoryReport::class,
        'PURCHASE_SUMMARY' => PurchaseSummaryReport::class,
        'PURCHASE_DETAIL' => PurchaseDetailReport::class,
        'PURCHASE_BY_SUPPLIER' => PurchaseBySupplierReport::class,
        'PURCHASE_BY_ITEM' => PurchaseByItemReport::class,
        'PURCHASE_BY_LOCATION_BU' => PurchaseByLocationBusinessUnitReport::class,
        'PURCHASE_OUTSTANDING_ORDERS' => PurchaseOutstandingOrdersReport::class,
        'PURCHASE_OUTSTANDING_RECEIPTS' => PurchaseOutstandingReceiptsReport::class,
        'VENDOR_OUTSTANDING' => VendorOutstandingReport::class,
        'VENDOR_STATEMENT' => VendorStatementReport::class,
        'VENDOR_AGING' => VendorAgingReport::class,

        'STOCK_AVAILABILITY' => StockAvailabilityReport::class,
        'STOCK_MOVEMENT' => StockMovementReport::class,
        'STOCK_CARD' => StockCardReport::class,
        'STOCK_VALUATION' => StockValuationReport::class,
        'NEGATIVE_STOCK' => NegativeStockReport::class,
        'REORDER_REPORT' => ReorderReport::class,
        'SLOW_MOVING' => SlowMovingReport::class,
        'DEAD_STOCK' => DeadStockReport::class,
        'FAST_MOVING' => FastMovingReport::class,
        'TRANSFER_HISTORY' => TransferHistoryReport::class,
        'COGS_DETAIL' => CogsDetailReport::class,
        'INVENTORY_AGING' => InventoryAgingReport::class,

        'GENERAL_LEDGER_DETAIL' => GeneralLedgerDetailReport::class,
        'ACCOUNT_MOVEMENT' => AccountMovementReport::class,
        'JOURNAL_REGISTER' => JournalRegisterReport::class,
        'TRIAL_BALANCE' => TrialBalanceReport::class,
        'BALANCE_SHEET' => BalanceSheetReport::class,
        'PROFIT_LOSS' => ProfitLossReport::class,
        'PROFIT_LOSS_BY_BU' => ProfitLossByBusinessUnitReport::class,
        'CASH_FLOW' => CashFlowReport::class,
        'AR_GL_RECONCILIATION' => ArGlReconciliationReport::class,
        'AP_GL_RECONCILIATION' => ApGlReconciliationReport::class,
        'INVENTORY_GL_RECONCILIATION' => InventoryGlReconciliationReport::class,

        'EXECUTIVE_SALES_DASHBOARD' => ExecutiveSalesDashboardReport::class,
        'EXECUTIVE_PURCHASE_DASHBOARD' => ExecutivePurchaseDashboardReport::class,
        'INVENTORY_HEALTH' => InventoryHealthReport::class,
        'WORKING_CAPITAL' => WorkingCapitalReport::class,
        'MONTHLY_PERFORMANCE' => MonthlyPerformanceReport::class,
        'BUSINESS_UNIT_PERFORMANCE' => BusinessUnitPerformanceReport::class,
    ],

    'datasources' => [
        'SALES_INVOICE_DETAIL' => SalesInvoiceDetailAdapter::class,
        'SALES_ORDER_DETAIL' => SalesOrderDetailAdapter::class,
        'CUSTOMER_LEDGER' => CustomerLedgerAdapter::class,
        'PURCHASE_INVOICE_DETAIL' => PurchaseInvoiceDetailAdapter::class,
        'PURCHASE_ORDER_DETAIL' => PurchaseOrderDetailAdapter::class,
        'VENDOR_LEDGER' => VendorLedgerAdapter::class,
        'INVENTORY_MOVEMENT' => InventoryMovementAdapter::class,
        'STOCK_POSITION' => StockPositionAdapter::class,
        'GENERAL_LEDGER' => GeneralLedgerAdapter::class,
        'ITEM_MASTER' => ItemMasterAdapter::class,
        'CUSTOMER_MASTER' => CustomerMasterAdapter::class,
        'SUPPLIER_MASTER' => SupplierMasterAdapter::class,
        'CHART_OF_ACCOUNTS' => ChartOfAccountsAdapter::class,
        'AUDIT_ACTIVITY' => AuditActivityAdapter::class,
    ],

    'preview_row_limit' => 500,
    'screen_row_limit' => 5000,
    'sql_timeout_seconds' => 60,
    'export_row_limit' => 25000,
    'sql_export_row_limit' => 25000,
    'reconciliation_tolerance' => 0.01,
    'performance_slow_p95_ms' => 3000,
];
