@extends('layouts.app')
@section('title','Report Performance')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-3"><div><div class="text-muted small text-uppercase fw-bold">Report Administration</div><h3 class="mb-1">Performance Monitor</h3><div class="text-muted">Execution metrics from report audit logs. Slow threshold: P95 ≥ {{ number_format($threshold,0,',','.') }} ms.</div></div><div class="d-flex gap-2"><a class="btn btn-light" href="{{ route('reports.center') }}">Report Center</a><form method="get" class="d-flex gap-2"><select class="form-select" name="days"><option value="7" @selected($days===7)>7 days</option><option value="30" @selected($days===30)>30 days</option><option value="90" @selected($days===90)>90 days</option><option value="365" @selected($days===365)>365 days</option></select><button class="btn btn-primary">Apply</button></form></div></div>
<div class="card"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead class="table-light"><tr><th>Report</th><th>Type</th><th class="text-end">Runs</th><th class="text-end">Avg ms</th><th class="text-end">P95 ms</th><th class="text-end">Max ms</th><th class="text-end">Avg Rows</th><th class="text-end">Failure %</th><th>Status</th></tr></thead><tbody>
@forelse($rows as $row)<tr><td><div class="fw-semibold">{{ $row['name'] }}</div><div class="small text-muted">{{ $row['code'] }} · {{ $row['category'] }}</div></td><td>{{ $row['type'] }}</td><td class="text-end">{{ number_format($row['run_count'],0,',','.') }}</td><td class="text-end">{{ number_format($row['avg_duration_ms'],0,',','.') }}</td><td class="text-end fw-semibold">{{ number_format($row['p95_duration_ms'],0,',','.') }}</td><td class="text-end">{{ number_format($row['max_duration_ms'],0,',','.') }}</td><td class="text-end">{{ number_format($row['avg_rows'],0,',','.') }}</td><td class="text-end">{{ number_format($row['failure_rate'],2,',','.') }}%</td><td>@if($row['slow'])<span class="badge text-bg-warning">Review</span>@else<span class="badge text-bg-success">Normal</span>@endif</td></tr>
@empty<tr><td colspan="9" class="text-center text-muted py-5">No report execution data for this period.</td></tr>@endforelse
</tbody></table></div></div>
<div class="alert alert-light border mt-3 mb-0"><strong>Optimization rule:</strong> fix query/index first. Materialized summaries are only introduced after execution logs prove a specific report remains slow.</div>
@endsection
