<?php
namespace App\Http\Controllers\Inventory;
use App\Http\Controllers\Controller;
use App\Models\{BusinessUnit,Item,Location,LocationBin};
use App\Models\Inventory\GoodsTransferRequest;
use App\Services\Audit\ActivityLogService;
use App\Services\Inventory\LocationBinService;
use App\Services\Pricing\ItemPriceService;
use App\Services\System\DocumentSequenceService;
use DomainException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GoodsTransferRequestController extends Controller {
 public function __construct(private DocumentSequenceService $numbers,private LocationBinService $binRules,private ActivityLogService $audit,private ItemPriceService $itemRules){}
 private function gate(Request $r,string $perm): void {abort_unless(app(\App\Services\Security\MenuAuthorizationService::class)->allows($r->user(),'inventory.transfer-requests',$perm),403);}
 public function index(Request $r){$this->gate($r,'view');$q=GoodsTransferRequest::with(['sourceLocation','destinationLocation','businessUnit'])->latest('id');if($r->filled('status'))$q->where('status',$r->input('status'));if($r->filled('q'))$q->where('document_no','like','%'.$r->input('q').'%');return view('inventory.transfer-requests.index',['rows'=>$q->paginate(30)->withQueryString()]);}
 public function create(Request $r){$this->gate($r,'create');return view('inventory.transfer-requests.form',$this->formData(new GoodsTransferRequest));}
 public function store(Request $r){$this->gate($r,'create');$d=$this->validated($r);$doc=DB::transaction(function()use($d){$h=$d['header'];$h['document_no']=$this->numbers->next('GOODS_TRANSFER_REQUEST');$h['created_by']=auth()->id();$doc=GoodsTransferRequest::create($h);foreach($d['lines'] as $line)$doc->lines()->create($line);$this->audit->record('inventory.transfer-requests','create',$doc,[],$doc->toArray(),['document_number'=>$doc->document_no]);return$doc;});return redirect()->route('goods-transfer-requests.show',$doc)->with('success','Transfer Request created.');}
 public function show(Request $r,GoodsTransferRequest $request){$this->gate($r,'view');$request->load(['lines.item','sourceLocation','destinationLocation','sourceBin','destinationBin','businessUnit']);return view('inventory.transfer-requests.show',['record'=>$request]);}
 public function release(Request $r,GoodsTransferRequest $request){$this->gate($r,'release');DB::transaction(function()use($request){$doc=GoodsTransferRequest::with('lines.item')->lockForUpdate()->findOrFail($request->id);if($doc->status!=='OPEN')throw new DomainException('Only OPEN request can be released.');foreach($doc->lines as $line)$this->itemRules->assertEligible($line->item);$doc->update(['status'=>'RELEASED','released_by'=>auth()->id(),'released_at'=>now()]);$this->audit->record('inventory.transfer-requests','release',$doc,[], $doc->toArray(),['document_number'=>$doc->document_no]);});return back()->with('success','Request released for approval.');}
 public function approve(Request $r,GoodsTransferRequest $request){$this->gate($r,'approve');DB::transaction(function()use($request){$doc=GoodsTransferRequest::with('lines.item')->lockForUpdate()->findOrFail($request->id);if($doc->status!=='RELEASED')throw new DomainException('Only RELEASED request can be approved.');foreach($doc->lines as $line)$this->itemRules->assertEligible($line->item);if((int)$doc->created_by===(int)auth()->id())throw new DomainException('Request creator cannot approve their own transfer request.');$doc->update(['status'=>'APPROVED','approved_by'=>auth()->id(),'approved_at'=>now()]);$this->audit->record('inventory.transfer-requests','approve',$doc,[], $doc->toArray(),['document_number'=>$doc->document_no]);});return back()->with('success','Request approved.');}
 public function reject(Request $r,GoodsTransferRequest $request){$this->gate($r,'approve');$reason=$r->validate(['reason'=>'required|string|max:1000'])['reason'];$doc=GoodsTransferRequest::lockForUpdate()->findOrFail($request->id);if($doc->status!=='RELEASED')throw new DomainException('Only RELEASED request can be rejected.');$doc->update(['status'=>'REJECTED','rejected_by'=>auth()->id(),'rejected_at'=>now(),'rejection_reason'=>$reason]);$this->audit->record('inventory.transfer-requests','reject',$doc,[], $doc->toArray(),['document_number'=>$doc->document_no]);return back()->with('success','Request rejected.');}
 private function validated(Request $r): array {$v=$r->validate(['business_unit_id'=>'nullable|exists:business_units,id','document_date'=>'required|date','source_location_id'=>'required|exists:locations,id','source_bin_id'=>'nullable|exists:location_bins,id','destination_location_id'=>'required|exists:locations,id','destination_bin_id'=>'nullable|exists:location_bins,id','notes'=>'nullable|string','lines'=>'required|array|min:1','lines.*.item_id'=>'required|exists:items,id','lines.*.quantity'=>'required|numeric|gt:0']);$src=Location::findOrFail($v['source_location_id']);$dst=Location::findOrFail($v['destination_location_id']);$srcBin=!empty($v['source_bin_id'])?LocationBin::find($v['source_bin_id']):null;$dstBin=!empty($v['destination_bin_id'])?LocationBin::find($v['destination_bin_id']):null;$this->binRules->validate($src,$srcBin);$this->binRules->validate($dst,$dstBin);if($src->id===$dst->id&&($srcBin?->id??0)===($dstBin?->id??0))throw new DomainException('Source and destination must be different.');$lines=[];foreach($v['lines'] as $line){$item=Item::findOrFail($line['item_id']);if($item->item_type!=='INVENTORY')throw new DomainException("Only inventory item can be transferred: {$item->code}");$this->itemRules->assertEligible($item);$lines[]=['item_id'=>$item->id,'quantity'=>$line['quantity'],'description'=>$item->name];}return ['header'=>['business_unit_id'=>$v['business_unit_id']??null,'document_date'=>$v['document_date'],'status'=>'OPEN','source_location_id'=>$src->id,'source_bin_id'=>$srcBin?->id,'destination_location_id'=>$dst->id,'destination_bin_id'=>$dstBin?->id,'notes'=>$v['notes']??null],'lines'=>$lines];}
 private function formData(GoodsTransferRequest $record): array{return ['record'=>$record,'businessUnits'=>BusinessUnit::where('is_active',true)->orderBy('code')->get(),'locations'=>Location::where('is_active',true)->where('is_system',false)->with('bins')->orderBy('code')->get(),'items'=>Item::where('is_active',true)->where('is_discontinued',false)->where('price_hold',false)->where('item_type','INVENTORY')->orderBy('code')->get()];}
}
