<?php
namespace App\Http\Controllers\Inventory;

use App\Http\Controllers\Controller;
use App\Models\Inventory\{GoodsTransfer,GoodsTransferRequest};
use App\Services\Audit\ActivityLogService;
use App\Services\Inventory\GoodsTransferPostingService;
use App\Services\Pricing\ItemPriceService;
use App\Services\System\DocumentSequenceService;
use DomainException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GoodsTransferController extends Controller {
 public function __construct(private DocumentSequenceService $numbers,private GoodsTransferPostingService $posting,private ActivityLogService $audit,private ItemPriceService $itemRules){}
 private function gate(Request $r,string $perm): void {abort_unless(app(\App\Services\Security\MenuAuthorizationService::class)->allows($r->user(),'inventory.transfers',$perm),403);}
 public function index(Request $r){$this->gate($r,'view');$q=GoodsTransfer::with(['sourceLocation','destinationLocation','businessUnit'])->latest('id');if($r->filled('status'))$q->where('status',$r->input('status'));return view('inventory.transfers.index',['rows'=>$q->paginate(30)->withQueryString()]);}
 public function create(Request $r,GoodsTransferRequest $request){$this->gate($r,'create');abort_unless($request->status==='APPROVED',422,'Only APPROVED request can create a Goods Transfer.');$request->load('lines.item');foreach($request->lines as $line)$this->itemRules->assertEligible($line->item);$existing=\App\Models\Inventory\GoodsTransferLine::whereHas('document',fn($q)=>$q->where('goods_transfer_request_id',$request->id)->where('status','!=','UNDO'))->selectRaw('goods_transfer_request_line_id,SUM(quantity) qty')->groupBy('goods_transfer_request_line_id')->pluck('qty','goods_transfer_request_line_id');$lines=$request->lines->map(fn($l)=>['request_line_id'=>$l->id,'item_id'=>$l->item_id,'item_code'=>$l->item->code,'name'=>$l->item->name,'remaining'=>max(0,(float)$l->quantity-(float)($existing[$l->id]??0))])->filter(fn($l)=>$l['remaining']>0)->values();return view('inventory.transfers.form',['requestDoc'=>$request,'lines'=>$lines]);}
 public function store(Request $r,GoodsTransferRequest $request){$this->gate($r,'create');$v=$r->validate(['document_date'=>'required|date','notes'=>'nullable|string','lines'=>'required|array|min:1','lines.*.request_line_id'=>'required|exists:goods_transfer_request_lines,id','lines.*.quantity'=>'required|numeric|gt:0','lines.*.unit_cost'=>'required|numeric|gt:0']);$doc=DB::transaction(function()use($request,$v){$req=GoodsTransferRequest::with('lines')->lockForUpdate()->findOrFail($request->id);if($req->status!=='APPROVED')throw new DomainException('Request is no longer approved.');$doc=GoodsTransfer::create(['document_no'=>$this->numbers->next('GOODS_TRANSFER'),'goods_transfer_request_id'=>$req->id,'business_unit_id'=>$req->business_unit_id,'document_date'=>$v['document_date'],'status'=>'OPEN','source_location_id'=>$req->source_location_id,'source_bin_id'=>$req->source_bin_id,'destination_location_id'=>$req->destination_location_id,'destination_bin_id'=>$req->destination_bin_id,'notes'=>$v['notes']??null,'created_by'=>auth()->id()]);foreach($v['lines'] as $raw){$line=$req->lines->firstWhere('id',(int)$raw['request_line_id']);if(!$line)throw new DomainException('Invalid request line.');$item=\App\Models\Item::findOrFail($line->item_id);$this->itemRules->assertEligible($item);$used=(float)\App\Models\Inventory\GoodsTransferLine::where('goods_transfer_request_line_id',$line->id)->whereHas('document',fn($q)=>$q->where('status','!=','UNDO'))->sum('quantity');$remaining=(float)$line->quantity-$used;if((float)$raw['quantity']>$remaining+0.0001)throw new DomainException("Transfer qty exceeds request remaining for line {$line->id}.");$doc->lines()->create(['goods_transfer_request_line_id'=>$line->id,'item_id'=>$line->item_id,'quantity'=>$raw['quantity'],'unit_cost'=>$raw['unit_cost']]);}$this->audit->record('inventory.transfers','create',$doc,[],$doc->toArray(),['document_number'=>$doc->document_no]);return$doc;});return redirect()->route('goods-transfers.show',$doc)->with('success','Goods Transfer created.');}
 public function show(Request $r,GoodsTransfer $transfer){$this->gate($r,'view');$transfer->load(['request','lines.item','sourceLocation','destinationLocation','sourceBin','destinationBin','businessUnit']);return view('inventory.transfers.show',['record'=>$transfer]);}
 public function release(Request $r,GoodsTransfer $transfer){$this->gate($r,'release');$doc=GoodsTransfer::with('lines.item')->lockForUpdate()->findOrFail($transfer->id);if($doc->status!=='OPEN')throw new DomainException('Only OPEN transfer can be released.');foreach($doc->lines as $line)$this->itemRules->assertEligible($line->item);$doc->update(['status'=>'RELEASED','released_by'=>auth()->id(),'released_at'=>now()]);$this->audit->record('inventory.transfers','release',$doc,[], $doc->toArray(),['document_number'=>$doc->document_no]);return back()->with('success','Transfer released.');}
 public function ship(Request $r,GoodsTransfer $transfer){$this->gate($r,'post');$this->posting->ship($transfer,(int)$r->user()->id);return back()->with('success','Goods shipped to Inventory In Transit.');}
 public function receive(Request $r,GoodsTransfer $transfer){$this->gate($r,'post');$d=$r->validate(['lines'=>'required|array','lines.*'=>'nullable|numeric|min:0','notes'=>'nullable|string']);$no=$this->posting->receive($transfer,$d['lines'],(int)$r->user()->id,$d['notes']??null);return back()->with('success',"Receipt {$no} posted.");}
 public function undo(Request $r,GoodsTransfer $transfer){$this->gate($r,'undo');$reason=$r->validate(['reason'=>'required|string|max:1000'])['reason'];$no=$this->posting->undo($transfer,$reason,(int)$r->user()->id);return back()->with('success',"Transfer undone with {$no}.");}
}
