@extends('layouts.app')
@section('title',$allocation->exists?'Edit Allocation':'New Allocation')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">{{ $allocation->exists?'Edit':'New' }} Employee Allocation</h4><div class="text-muted small">Periods for one employee cannot overlap.</div></div><a class="btn btn-outline-secondary" href="{{ route('hr.allocations.index') }}">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ $allocation->exists?route('hr.allocations.update',$allocation):route('hr.allocations.store') }}">@csrf @if($allocation->exists)@method('PUT')@endif
<div class="card"><div class="card-body row g-3">
<div class="col-md-6"><label class="form-label">Employee</label><select class="form-select" name="employee_id" required><option value="">Select...</option>@foreach($employees as $e)<option value="{{ $e->id }}" @selected((string)old('employee_id',$allocation->employee_id)===(string)$e->id)>{{ $e->employee_code }} - {{ $e->full_name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Effective From</label><input type="date" class="form-control" name="effective_from" value="{{ old('effective_from',optional($allocation->effective_from)->format('Y-m-d')) }}" required></div><div class="col-md-3"><label class="form-label">Effective To</label><input type="date" class="form-control" name="effective_to" value="{{ old('effective_to',optional($allocation->effective_to)->format('Y-m-d')) }}"><div class="form-text">Blank = current/open ended</div></div>
<div class="col-md-4"><label class="form-label">Business Unit</label><select class="form-select" name="business_unit_id"><option value="">-</option>@foreach($businessUnits as $r)<option value="{{ $r->id }}" @selected((string)old('business_unit_id',$allocation->business_unit_id)===(string)$r->id)>{{ $r->code }} - {{ $r->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Department</label><select class="form-select" name="department_id"><option value="">-</option>@foreach($departments as $r)<option value="{{ $r->id }}" @selected((string)old('department_id',$allocation->department_id)===(string)$r->id)>{{ $r->code }} - {{ $r->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Sub Department</label><select class="form-select" name="sub_department_id"><option value="">-</option>@foreach($subDepartments as $r)<option value="{{ $r->id }}" @selected((string)old('sub_department_id',$allocation->sub_department_id)===(string)$r->id)>{{ $r->code }} - {{ $r->name }}</option>@endforeach</select></div>
@php $sets=[['position_id','Position',$positions],['level_id','Level',$levels],['group_id','Group',$groups],['workgroup_id','Workgroup',$workgroups],['team_id','Team',$teams],['office_location_id','Office Location',$officeLocations],['payroll_group_id','Payroll Group',$payrollGroups]]; @endphp
@foreach($sets as [$name,$label,$rows])<div class="col-md-4"><label class="form-label">{{ $label }}</label><select class="form-select" name="{{ $name }}"><option value="">-</option>@foreach($rows as $r)<option value="{{ $r->id }}" @selected((string)old($name,$allocation->{$name})===(string)$r->id)>{{ $r->code }} - {{ $r->name }}</option>@endforeach</select></div>@endforeach
<div class="col-md-4"><label class="form-label">Report To</label><select class="form-select" name="report_to_employee_id"><option value="">-</option>@foreach($employees as $e)<option value="{{ $e->id }}" @selected((string)old('report_to_employee_id',$allocation->report_to_employee_id)===(string)$e->id)>{{ $e->employee_code }} - {{ $e->full_name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Employment Status</label><input class="form-control" name="employment_status" value="{{ old('employment_status',$allocation->employment_status) }}" placeholder="PERMANENT / CONTRACT / etc"></div><div class="col-md-4"><label class="form-label">Job Status</label><input class="form-control" name="job_status" value="{{ old('job_status',$allocation->job_status) }}"></div><div class="col-md-4"><label class="form-label">Contract No.</label><input class="form-control" name="contract_no" value="{{ old('contract_no',$allocation->contract_no) }}"></div><div class="col-md-4"><label class="form-label">Contract Expiry</label><input type="date" class="form-control" name="contract_expiry_date" value="{{ old('contract_expiry_date',optional($allocation->contract_expiry_date)->format('Y-m-d')) }}"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2">{{ old('notes',$allocation->notes) }}</textarea></div>
</div><div class="card-footer bg-white"><button class="btn btn-primary">Save Allocation</button></div></div></form>
@endsection
