@extends('layouts.app')
@section('title','New Goods Transfer Request')
@section('content')
<h4 class="mb-3">New Goods Transfer Request</h4>
<form method="post" action="{{ route('goods-transfer-requests.store') }}">@csrf
<div class="card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-3"><label class="form-label">Date</label><input type="date" class="form-control" name="document_date" value="{{ now()->toDateString() }}" required></div><div class="col-md-4"><label class="form-label">Source Location</label><select class="form-select" name="source_location_id" id="src-location" required><option value="">Select</option>@foreach($locations as $l)<option value="{{ $l->id }}">{{ $l->code }} - {{ $l->name }}{{ $l->bin_mandatory?' (Bin Required)':'' }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Source Bin</label><select class="form-select" name="source_bin_id"><option value="">-</option>@foreach($locations as $l)@foreach($l->bins as $b)<option value="{{ $b->id }}">{{ $l->code }} / {{ $b->code }}</option>@endforeach @endforeach</select></div><div class="col-md-4"><label class="form-label">Destination Location</label><select class="form-select" name="destination_location_id" required><option value="">Select</option>@foreach($locations as $l)<option value="{{ $l->id }}">{{ $l->code }} - {{ $l->name }}{{ $l->bin_mandatory?' (Bin Required)':'' }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Destination Bin</label><select class="form-select" name="destination_bin_id"><option value="">-</option>@foreach($locations as $l)@foreach($l->bins as $b)<option value="{{ $b->id }}">{{ $l->code }} / {{ $b->code }}</option>@endforeach @endforeach</select></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes"></textarea></div></div></div></div>
<div class="card"><div class="card-header bg-white d-flex justify-content-between"><strong>Items</strong><button type="button" class="btn btn-sm btn-outline-primary" id="add-line">+ Add</button></div><table class="table mb-0"><thead><tr><th>Item</th><th>Qty</th><th></th></tr></thead><tbody id="lines"></tbody></table><div class="card-body border-top"><button class="btn btn-primary">Save Request</button></div></div></form>
<template id="line-tpl"><tr><td><select class="form-select item" required><option value="">Select item</option>@foreach($items as $i)<option value="{{ $i->id }}">{{ $i->code }} - {{ $i->name }}</option>@endforeach</select></td><td><input type="number" step="0.0001" min="0.0001" class="form-control qty" required></td><td><button type="button" class="btn btn-outline-danger rm">×</button></td></tr></template>
@push('scripts')<script>(()=>{const box=document.getElementById('lines'),tpl=document.getElementById('line-tpl');const ren=()=>[...box.children].forEach((r,i)=>{r.querySelector('.item').name=`lines[${i}][item_id]`;r.querySelector('.qty').name=`lines[${i}][quantity]`});document.getElementById('add-line').onclick=()=>{box.append(tpl.content.cloneNode(true));ren()};box.addEventListener('click',e=>{if(e.target.classList.contains('rm')){e.target.closest('tr').remove();ren()}});document.getElementById('add-line').click()})();</script>@endpush
@endsection
