@extends('layouts.app')
@section('title',$record->document_no)
@section('content')
@php $authz=app(\App\Services\Security\MenuAuthorizationService::class); @endphp
<div class="d-flex justify-content-between mb-3"><div><h4 class="mb-0">{{ $record->document_no }}</h4><span class="status-badge status-{{ $record->status }}">{{ $record->status }}</span></div><a class="btn btn-outline-secondary" href="{{ route('goods-transfer-requests.index') }}">Back</a></div>
<div class="card mb-3"><div class="card-body"><div><strong>Route:</strong> {{ $record->sourceLocation?->code }}{{ $record->sourceBin?' / '.$record->sourceBin->code:'' }} → {{ $record->destinationLocation?->code }}{{ $record->destinationBin?' / '.$record->destinationBin->code:'' }}</div><div><strong>Date:</strong> {{ $record->document_date }}</div><div><strong>Notes:</strong> {{ $record->notes?:'-' }}</div></div></div>
<div class="card mb-3"><table class="table mb-0"><thead><tr><th>Item</th><th>Qty</th></tr></thead><tbody>@foreach($record->lines as $l)<tr><td>{{ $l->item?->code }} - {{ $l->item?->name }}</td><td>{{ number_format((float)$l->quantity,4) }}</td></tr>@endforeach</tbody></table></div>
<div class="d-flex gap-2 flex-wrap">@if($record->status==='OPEN'&&$authz->allows(auth()->user(),'inventory.transfer-requests','release'))<form method="post" action="{{ route('goods-transfer-requests.release',$record) }}">@csrf<button class="btn btn-warning">Release</button></form>@endif @if($record->status==='RELEASED'&&$authz->allows(auth()->user(),'inventory.transfer-requests','approve'))<form method="post" action="{{ route('goods-transfer-requests.approve',$record) }}">@csrf<button class="btn btn-success">Approve</button></form><form method="post" action="{{ route('goods-transfer-requests.reject',$record) }}" class="d-flex gap-2">@csrf<input class="form-control" name="reason" placeholder="Reject reason" required><button class="btn btn-outline-danger">Reject</button></form>@endif @if($record->status==='APPROVED')<a class="btn btn-primary" href="{{ route('goods-transfers.create',$record) }}">Create Goods Transfer</a>@endif</div>
@endsection
