<?php
namespace App\Http\Controllers\Configuration;
use App\Http\Controllers\Controller; use App\Models\SystemSetting; use App\Services\Audit\ActivityLogService; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException;
class SystemSettingController extends Controller { public function __construct(){ $this->middleware('menu.permission:config.settings,view')->only('index');$this->middleware('menu.permission:config.settings,create')->only(['create','store']);$this->middleware('menu.permission:config.settings,edit')->only(['edit','update']); }
 public function index(){return view('configuration.settings.index',['rows'=>SystemSetting::orderBy('key')->get()]);} public function create(){return view('configuration.settings.form',['record'=>new SystemSetting(['value_type'=>'string']),'isEdit'=>false]);}
 private function data(Request $r,?int $id=null): array{$d=$r->validate(['key'=>['required','string','max:150',Rule::unique('system_settings','key')->ignore($id)],'value'=>['nullable','string'],'value_type'=>['required','in:string,integer,decimal,boolean,json'],'description'=>['nullable','string'],'is_public'=>['required','boolean']]);$v=$d['value'];$valid=match($d['value_type']){'integer'=>$v===null||filter_var($v,FILTER_VALIDATE_INT)!==false,'decimal'=>$v===null||is_numeric($v),'boolean'=>in_array(strtolower((string)$v),['1','0','true','false','yes','no'],true),'json'=>$v===null||$this->validJson($v),default=>true};if(!$valid)throw ValidationException::withMessages(['value'=>'Value does not match selected type.']);return $d;}
 private function validJson(?string $value): bool { if($value===null)return true; json_decode($value,true); return json_last_error()===JSON_ERROR_NONE; }
 public function store(Request $r,ActivityLogService $audit){$m=SystemSetting::create($this->data($r));$audit->record('config.settings','create',$m,[],$m->toArray());return redirect()->route('config.settings.index')->with('success','Setting created.');} public function edit(SystemSetting $setting){return view('configuration.settings.form',['record'=>$setting,'isEdit'=>true]);} public function update(Request $r,SystemSetting $setting,ActivityLogService $audit){$before=$setting->toArray();$setting->update($this->data($r,$setting->id));$audit->record('config.settings','update',$setting,$before,$setting->fresh()->toArray());return redirect()->route('config.settings.index')->with('success','Setting updated.');}
}
