@extends('layouts.app')
@section('title','Work Schedules')
@section('content')
<div class="mb-3"><h4 class="mb-1">Work Schedules</h4><div class="small text-muted">Priority: date override → effective employee pattern → no schedule. OFF days are explicit.</div></div>
<div class="row g-3 mb-3">
<div class="col-xl-7"><div class="card h-100"><div class="card-header bg-white"><strong>Shift Patterns</strong></div><div class="card-body">
@foreach($patterns as $pattern)
<form class="border rounded p-3 mb-3" method="post" action="{{ route('hr.schedules.patterns.update',$pattern) }}">@csrf @method('PUT')
<div class="row g-2"><div class="col-md-3"><input class="form-control" name="code" value="{{ $pattern->code }}" required></div><div class="col-md-5"><input class="form-control" name="name" value="{{ $pattern->name }}" required></div><div class="col-md-2 form-check mt-3 ms-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" name="is_active" value="1" type="checkbox" @checked($pattern->is_active)><label class="form-check-label">Active</label></div></div>
<div class="row g-2 mt-2">@php($dayNames=[1=>'Mon',2=>'Tue',3=>'Wed',4=>'Thu',5=>'Fri',6=>'Sat',7=>'Sun']) @foreach($dayNames as $n=>$label) @php($d=$pattern->days->firstWhere('weekday',$n)) <div class="col"><label class="form-label small">{{ $label }}</label><select class="form-select form-select-sm" name="days[{{ $n }}]"><option value="OFF" @selected($d?->is_off || !$d)>OFF</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}" @selected(!$d?->is_off && (int)$d?->shift_id===(int)$shift->id)>{{ $shift->code }}</option>@endforeach</select></div>@endforeach</div>
<button class="btn btn-sm btn-outline-primary mt-3">Update Pattern</button></form>
@endforeach
<hr><h6>New Pattern</h6><form method="post" action="{{ route('hr.schedules.patterns.store') }}">@csrf<div class="row g-2"><div class="col-md-3"><input class="form-control" name="code" placeholder="WEEK-5" required></div><div class="col-md-5"><input class="form-control" name="name" placeholder="Normal Week" required></div><div class="col-md-2 form-check mt-2 ms-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" name="is_active" value="1" type="checkbox" checked><label class="form-check-label">Active</label></div></div><div class="row g-2 mt-2">@foreach([1=>'Mon',2=>'Tue',3=>'Wed',4=>'Thu',5=>'Fri',6=>'Sat',7=>'Sun'] as $n=>$label)<div class="col"><label class="form-label small">{{ $label }}</label><select class="form-select form-select-sm" name="days[{{ $n }}]"><option value="OFF">OFF</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->code }}</option>@endforeach</select></div>@endforeach</div><button class="btn btn-primary btn-sm mt-3">Create Pattern</button></form>
</div></div></div>
<div class="col-xl-5"><div class="card mb-3"><div class="card-header bg-white"><strong>Assign Pattern to Employee</strong></div><div class="card-body"><form method="post" action="{{ route('hr.schedules.assignments.store') }}">@csrf<div class="row g-2"><div class="col-12"><select class="form-select" name="employee_id" required><option value="">Employee</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_code }} - {{ $e->full_name }}</option>@endforeach</select></div><div class="col-12"><select class="form-select" name="shift_pattern_id" required><option value="">Pattern</option>@foreach($patterns->where('is_active',true) as $p)<option value="{{ $p->id }}">{{ $p->code }} - {{ $p->name }}</option>@endforeach</select></div><div class="col-6"><input type="date" class="form-control" name="effective_from" required></div><div class="col-6"><input type="date" class="form-control" name="effective_to"></div><div class="col-12"><textarea class="form-control" name="notes" placeholder="Notes"></textarea></div></div><button class="btn btn-primary btn-sm mt-2">Assign</button></form></div></div>
<div class="card"><div class="card-header bg-white"><strong>Date Override</strong></div><div class="card-body"><form method="post" action="{{ route('hr.schedules.overrides.store') }}">@csrf<div class="row g-2"><div class="col-12"><select class="form-select" name="employee_id" required><option value="">Employee</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_code }} - {{ $e->full_name }}</option>@endforeach</select></div><div class="col-6"><input type="date" class="form-control" name="work_date" required></div><div class="col-6"><select class="form-select" name="shift_id"><option value="">Shift</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->code }}</option>@endforeach</select></div><div class="col-12"><input type="hidden" name="is_off" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_off" value="1"><label class="form-check-label">Override as OFF day</label></div></div><div class="col-12"><textarea class="form-control" name="notes" placeholder="Reason / notes"></textarea></div></div><button class="btn btn-outline-primary btn-sm mt-2">Save Override</button></form></div></div></div>
</div>
<div class="card mb-3"><div class="card-header bg-white"><strong>Effective Employee Assignments</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Employee</th><th>Pattern</th><th>Effective</th><th>Notes</th><th></th></tr></thead><tbody>@forelse($assignments as $a)<tr><td>{{ $a->employee?->employee_code }} - {{ $a->employee?->full_name }}</td><td>{{ $a->pattern?->code }}</td><td>{{ optional($a->effective_from)->format('d/m/Y') }} → {{ optional($a->effective_to)->format('d/m/Y') ?: 'Current' }}</td><td>{{ $a->notes }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('hr.schedules.assignments.edit',$a) }}">Edit</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-3">No assignment.</td></tr>@endforelse</tbody></table></div></div><div class="mb-3">{{ $assignments->links() }}</div>
<div class="card"><div class="card-header bg-white"><strong>Recent Date Overrides</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Employee</th><th>Result</th><th>Notes</th></tr></thead><tbody>@forelse($overrides as $o)<tr><td>{{ optional($o->work_date)->format('d/m/Y') }}</td><td>{{ $o->employee?->employee_code }} - {{ $o->employee?->full_name }}</td><td>{{ $o->is_off?'OFF':($o->shift?->code??'-') }}</td><td>{{ $o->notes }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">No override.</td></tr>@endforelse</tbody></table></div></div>
@endsection
